<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Major;

class MajorSeeder extends Seeder
{
    public function run(): void
    {
        $lisansMajors = [
            ['name' => 'Acil Yardım ve Afet Yönetimi', 'desc' => 'Deprem, yangın, sel gibi afetlerin öncesinde risk analizi yapan; afet anında müdahaleyi yöneten ve sonrasında iyileştirme süreçlerini koordine eden uzmanlar yetiştirir.'],
            ['name' => 'Adli Bilimler', 'desc' => 'Suç mahalinden toplanan fiziksel ve biyolojik delillerin (DNA, parmak izi, balistik vb.) laboratuvar ortamında bilimsel yöntemlerle analiz edilerek hukuki sürece katkı sunulmasını sağlar.'],
            ['name' => 'Adli Bilişim Mühendisliği', 'desc' => 'Bilgisayar, akıllı telefon ve ağ sistemleri üzerinden işlenen siber suçların izini süren, dijital delilleri hukuka uygun şekilde kurtaran ve analiz eden mühendislik dalıdır.'],
            ['name' => 'Ağaç İşleri Endüstri Mühendisliği', 'desc' => 'Ağaç bazlı hammaddelerin işlenerek mobilya, ahşap yapı elemanları gibi ürünlere dönüştürülmesi sürecindeki tasarımı, üretimi ve fabrika yönetimini kapsار.'],
            ['name' => 'Aile ve Tüketici Bilimleri', 'desc' => 'Bireylerin ve ailelerin yaşam kalitesini artırmak için; kaynak yönetimi (bütçe, zaman), tüketici hakları, beslenme ve çevre yönetimi konularında eğitim ve danışmanlık verir.'],
            ['name' => 'Aktüerya Bilimleri', 'desc' => 'Gelecekteki finansal riskleri, belirsizlikleri ve olası olayların mali sonuçlarını matematiksel ve istatistiksel yöntemlerle hesaplayan (sigortacılık, emeklilik gibi) uzmanlık alanıdır.'],
            ['name' => 'Alman Dili ve Edebiyatı', 'desc' => 'Alman dilinin yapısını, tarihsel gelişimini ve Alman kültürünün ürettiği edebi eserleri derinlemesine inceleyerek kültürel ve akademik analiz yetisi kazandırır.'],
            ['name' => 'Almanca Mütercim ve Tercümanlık', 'desc' => 'Almanca ve Türkçe arasında profesyonel düzeyde yazılı metin çevirisi ve sözlü (simültane/ardıl) çeviri yapabilecek dil uzmanları yetiştirir.'],
            ['name' => 'Almanca Öğretmenliği', 'desc' => 'Almancayı yabancı dil olarak öğretmek üzere; dil bilgisi, öğretim metodolojileri ve pedagojik formasyon üzerine eğitim verir.'],
            ['name' => 'Amerikan Kültürü ve Edebiyatı', 'desc' => 'Amerika Birleşik Devletleri\'nin tarihini, toplumsal yapısını, siyasi gelişimini ve edebi eserlerini İngilizce dil yetkinliğiyle birlikte inceler.'],
            ['name' => 'Arap Dili ve Edebiyatı', 'desc' => 'Arapça dil bilgisi yapısını, klasik ve modern Arap edebiyatını ve bu dilin kültürel mirasını akademik bir bakış açısıyla ele alır.'],
            ['name' => 'Arapça Mütercim ve Tercümanlık', 'desc' => 'Arapça ile Türkçe arasında her türlü ticari, hukuki, edebi ve anlık görüşmede çeviri yapabilecek profesyoneller yetiştirir.'],
            ['name' => 'Arapça Öğretmenliği', 'desc' => 'Arapça dilini her seviyedeki öğrenci grubuna etkili yöntemlerle öğretmek için gerekli dilsel ve pedagojik becerileri kazandırır.'],
            ['name' => 'Antrenörlük Eğitimi', 'desc' => 'Spor branşlarına özgü teknik ve taktik eğitimi verebilen, sporcu performansını analiz eden ve antrenman programları hazırlayan spor uzmanları yetiştirir.'],
            ['name' => 'Antropoloji', 'desc' => 'İnsanı; biyolojik, kültürel ve sosyal yönleriyle evrimsel bir süreç içinde inceleyen, toplumların fiziksel ve kültürel çeşitliliğine odaklanan bilim dalıdır.'],
            ['name' => 'Arkeoloji', 'desc' => 'Geçmişteki insan topluluklarının yaşamlarını, kültürlerini ve faaliyetlerini geride bıraktıkları maddi kalıntılar (mimari yapılar, araç-gereçler vb.) üzerinden kazı yaparak inceler.'],
            ['name' => 'Arkeoloji ve Sanat Tarihi', 'desc' => 'Arkeolojik buluntuların yanı sıra; mimarlık, resim ve heykel gibi görsel sanatların tarihsel gelişimini, üsluplarını ve toplumsal bağlamlarını bir bütün olarak ele alır.'],
            ['name' => 'Bilgisayar Mühendisliği', 'desc' => 'Bilgisayar sistemlerinin hem yazılım hem de donanım katmanlarını tasarlayan, geliştiren ve sistemlerin birbirleriyle entegrasyonunu sağlayan mühendislik dalıdır.'],
            ['name' => 'Bilgisayar Bilimleri', 'desc' => 'Hesaplama teorisi, algoritmalar, veri yapıları ve yapay zeka gibi yazılımın matematiksel ve teorik temellerine odaklanan bilim alanıdır.'],
            ['name' => 'Bilgi Güvenliği Teknolojisi', 'desc' => 'Dijital verilerin korunması, siber saldırıların önlenmesi ve ağ güvenliğinin sağlanması için teknik stratejiler geliştiren uzmanlık alanıdır.'],
            ['name' => 'Bilgisayar Teknolojisi ve Bilişim Sistemleri', 'desc' => 'Bilgisayar teknolojilerinin işletme ve yönetim süreçlerine entegrasyonuna odaklanan, uygulama ağırlıklı bir bölümdür.'],
            ['name' => 'Basım Teknolojileri', 'desc' => 'Gazete, kitap, ambalaj gibi materyallerin baskı öncesi, baskı aşaması ve baskı sonrası teknik süreçlerini ve kullanılan makinelerin yönetimini kapsar.'],
            ['name' => 'Astronomi ve Uzay Bilimleri', 'desc' => 'Gök cisimlerinin (yıldızlar, gezegenler, galaksiler) fiziksel ve kimyasal yapılarını, evrenin işleyişini ve uzay araştırmalarını konu alan temel bilim dalıdır.'],
            ['name' => 'Beslenme ve Diyetetik', 'desc' => 'Besinlerin sağlığa etkilerini inceleyen; bireylere ve toplumlara sağlıklı beslenme alışkanlığı kazandıran, hastalıkların tedavisinde diyet programları hazırlayan alandır.'],
            ['name' => 'Bahçe Bitkileri', 'desc' => 'Meyve, sebze, bağ ve süs bitkilerinin ıslahı, yetiştirilmesi, depolanması ve pazarlanması üzerine uzmanlık kazandırır.'],
            ['name' => 'Balıkçılık Teknolojisi Mühendisliği', 'desc' => 'Deniz ve iç su kaynaklarının korunması, su ürünleri avcılığı ve yetiştiriciliği ile bu ürünlerin işlenmesi süreçlerini yöneten mühendislik dalıdır.'],
            ['name' => 'Bankacılık ve Finans', 'desc' => 'Para piyasaları, yatırım araçları, portföy yönetimi ve finansal analiz konularında uzmanlaşarak ekonomik değer yaratma süreçlerini yönetir.'],
            ['name' => 'Bankacılık ve Sigortacılık', 'desc' => 'Bankacılık işlemlerinin yanı sıra risk yönetimi ve sigorta poliçelerinin oluşturulması, hasar tespiti gibi operasyonel süreçlere odaklanır.'],
            ['name' => 'Basın ve Yayın', 'desc' => 'Gazetecilik, editörlük ve yayıncılık dünyasına yönelik; haber toplama, yazمة، dijital ve basılı medya içerik üretimi süreçlerini kapsar.'],
            ['name' => 'Bilgi ve Belge Yönetimi', 'desc' => 'Kütüphaneler, arşivler ve bilgi merkezlerindeki verilerin düzenlenmesi, korunması ve erişilebilir hale getirilmesi süreçlerini yönetir.'],
            ['name' => 'Beden Eğitimi ve Spor Öğretmenliği', 'desc' => 'Okullarda spor kültürünü yaygınlaştırmak, öğrencilerin fiziksel gelişimini desteklemek ve hareket eğitimini pedagojik yöntemlerle vermek üzere öğretmenler yetiştirir.'],
            ['name' => 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği', 'desc' => 'Bilişim teknolojilerinin eğitim süreçlerine entegrasyonunu sağlayan, eğitim yazılımları geliştiren ve teknoloji derslerini yürüten eğitimciler yetiştirir.'],
            ['name' => 'Azerbaycan Türkçesi ve Edebiyatı', 'desc' => 'Azerbaycan Türkçesinin dil yapısını, tarihini ve bu dille üretilmiş zengin edebi mirası akademik düzeyde inceler.'],
            ['name' => 'Bilim Tarihi', 'desc' => 'Bilimsel düşüncenin antik çağlardan günümüزه gelişimini, büyük keşiflerin toplumsal etkilerini ve bilim insanlarının yöntemlerini tarihsel bir perspektifle ele alır.'],
            ['name' => 'Bilişim Sistemleri Mühendisliği', 'desc' => 'Kurumların bilgi teknolojisi altyapısını tasarlayan, yazılım ve donanımı iş hedefleriyle birleştiren, mühendislik yaklaşımlarıyla sistem kuran bölümdür.'],
            ['name' => 'Bilişim Sistemleri ve Teknolojileri', 'desc' => 'Teknolojinin işletme süreçlerine uygulanmasına odaklanır; yazılım geliştirme, veri tabanı yönetimi ve ağ sistemleri üzerine pratik uygulama becerisi kazandırır.'],
            ['name' => 'Bitki Koruma', 'desc' => 'Tarımsal ürünlere zarar veren hastalıklar, zararlılar ve yabancı otlarla bilimsel mücadele yöntemlerini (biyolojik, kimyasal ve kültürel) konu alan uzmanlık dalıdır.'],
            ['name' => 'Bitkisel Üretim ve Teknolojileri', 'desc' => 'Tarla bitkileri, bahçe bitkileri ve tohumculuk gibi alanlarda verimliliği artırmak için modern yetiştirme tekniklerini ve teknolojilerini inceler.'],
            ['name' => 'Biyokimya', 'desc' => 'Canlı organizmaların yapısındaki kimyasal maddeleri (proteinler, lipidler, DNA vb.) ve bu maddelerin yaşamı sürdüren kimyasal süreçlerini moleküler düzeyde inceler.'],
            ['name' => 'Biyoloji', 'desc' => 'Tüm canlıların yapısını, işleyişini, evrimini ve birbirleriyle olan etkileşimlerini hücreden ekosisteme kadar her boyutta inceleyen temel bilim dalıdır.'],
            ['name' => 'Biyoloji Öğretmenliği', 'desc' => 'Biyoloji biliminin temel prensiplerini ortaöğretim seviyesindeki öğrencilere aktarmak üzere pedagojik ve bilimsel eğitim veren öğretmenlik dalıdır.'],
            ['name' => 'Biyomedikal Mühendisliği', 'desc' => 'Mühendislik prensiplerini tıp ve biyolojiye uygulayarak; tıbbi cihazlar (MR, protezler, yapay organlar) ve teşhis/tedavi yöntemleri geliştiren daldır.'],
            ['name' => 'Biyomühendislik', 'desc' => 'Biyolojik sistemleri ve organizmaları mühendislik bakış açısıyla analiz ederek; endüstriyel, sağlık ve çevre sorunlarına biyolojik çözümler üretir.'],
            ['name' => 'Biyosistem Mühendisliği', 'desc' => 'Mühendisliği tarım ve biyolojik kaynaklara uygulayan; tarım makinaları, sulama sistemleri ve yenilenebilir enerji gibi konulara odaklanan disiplindir.'],
            ['name' => 'Biyoteknoloji', 'desc' => 'Canlı hücreleri veya biyolojik sistemleri kullanarak ilaç, gıda, tarım ve endüstri için yeni ürünler geliştirme sürecidir.'],
            ['name' => 'Çağdaş Türk Lehçeleri ve Edebiyatları', 'desc' => 'Türk dünyasındaki farklı lehçeleri (Kazak, Kırgız, Özbek, Tatar vb.) ve bu dillerin edebi eserlerini dilbilimsel ve kültürel açıdan inceler.'],
            ['name' => 'Çalışma Ekonomisi ve Endüstri İlişkileri (ÇEEİ)', 'desc' => 'Çalışma hayatını ekonomik, sosyal ve hukuki boyutlarıyla ele alır; sendikalar, iş hukuku ve insan kaynakları yönetimi üzerine uzmanlaşır.'],
            ['name' => 'Cevher Hazırlama Mühendisliği', 'desc' => 'Madenlerden çıkarılan ham cevherlerin, ekonomik değeri olan minerallere ayrıştırılması, zenginleştirilmesi ve sanayiye uygun hale getirilmesi süreçlerini yönetir.'],
            ['name' => 'Çeviribilimi', 'desc' => 'Yazılı ve sözlü çevirinin teorik temellerini, tekniklerini ve farklı kültürler arası iletişimdeki rolünü akademik bir perspektifle inceler.'],
            ['name' => 'Çevre Mühendisliği', 'desc' => 'Hava, su ve toprak kirliliğinin önlenmesi; atık yönetimi ve sürdürülebilir çevre politikaları geliştirilmesi için mühendislik çözümleri üretir.'],
            ['name' => 'Çin Dili ve Edebiyatı', 'desc' => 'Çince dil bilgisi yapısını, tarihini ve Çin kültürünün ürettiği edebi eserleri inceleyerek dil yetkinliği ve kültürel uzmanlık kazandırır.'],
            ['name' => 'Çizgi Film ve Animasyon', 'desc' => 'Karakter tasarımı, hikaye anlatımı ve hareket tekniklerini kullanarak 2-3 boyutlu dijital veya geleneksel animasyonlar üretme sanatıdır.'],
            ['name' => 'Dijital Oyun Tasarımı', 'desc' => 'Bir oyunun mekaniklerini, sanatsal dünyasını ve yazılım altyapısını birleştirerek kullanıcı deneyimi yüksek dijital oyunlar geliştirme sürecidir.'],
            ['name' => 'El Sanatları', 'desc' => 'Geleneksel ve modern tekniklerle dokuma, seramik, kuyumculuk gibi el emeğine dayalı estetik ve fonksiyonel ürünler tasarlama ve üretme alanıdır.'],
            ['name' => 'Çince Mütercim ve Tercümanlık', 'desc' => 'Çince ve Türkçe dilleri arasında profesyonel düzeyde yazılı metin ve sözlü konuşما çevirisi yapabilecek, iki kültür arasında köprü kuracak uzmanlar yetiştirir.'],
            ['name' => 'Dilbilimi', 'desc' => 'Dilin yapısını, ses birimlerini, söz dizimini ve anlamını bilimsel bir yöntemle inceleyen, dillerين evrimini araştıran daldır.'],
            ['name' => 'Coğrafya', 'desc' => 'Yeryüzünün fiziksel özelliklerini ve insanın çevreyle olan etkileşimini, toplumsal ve ekonomik yansımalarıyla inceleyen temel bilimdir.'],
            ['name' => 'Coğrafya Öğretmenliği', 'desc' => 'Coğrafya konularını ortaöğretim müfredatına uygun şekilde pedagojik yöntemlerle öğrencilere aktaracak eğitimciler yetiştirir.'],
            ['name' => 'Diş Hekimliği', 'desc' => 'Ağız, diş ve diş eti sağlığını koruma, hastalıkları teşhis etme ve cerrahi/protez yöntemlerle tedavi etme yetkinliği kazandıran tıp dalıdır.'],
            ['name' => 'Eczacılık', 'desc' => 'İlaçların geliştirilmesi, üretimi, etkileşimleri ve hastalara doğru şekilde ulaştırılması konusunda uzmanlaşan, kimya ve biyoloji ağırlıklı sağlık bilimidir.'],
            ['name' => 'Dil ve Konuşma Terapisi', 'desc' => 'Bireylerin konuşma, dil, ses ve yutma bozukluklarını teşhis eden ve bu sorunlara yönelik rehabilitasyon programları uygulayan uzmanlık alanıdır.'],
            ['name' => 'Ebelik', 'desc' => 'Gebelik süreci, doğum anı ve doğum sonrası dönemde anne ve bebek sağlığını takip eden, sağlıklı doğum sürecini yöneten profesyonel alandır.'],
            ['name' => 'Çocuk Gelişimi', 'desc' => '0-18 yaş arasındaki çocukların zihinsel, fiziksel, sosyal ve duygusal gelişimlerini takip eden, gelişimsel sorunlara yönelik destek programları üreten daldır.'],
            ['name' => 'Ekonomi (İktisat)', 'desc' => 'Kaynakların sınırlı olduğu bir dünyada üretim, tüketim ve bölüşüm süreçlerini, piyasa işleyişini ve devlet politikalarını analiz eder.'],
            ['name' => 'Ekonometri', 'desc' => 'Ekonomik teorileri ve modelleri matematiksel, istatistiksel ve bilgisayar tabanlı yöntemlerle test eden, veri odaklı tahminler yapan uzmanlık dalıdır.'],
            ['name' => 'Ekonomi ve Finans', 'desc' => 'Ekonomi teorilerini, finansal piyasalar, yatırım araçları ve kurumsal finans yönetimi gibi uygulama alanlarıyla birleştirir.'],
            ['name' => 'Deniz Ulaştırma İşletme Mühendisliği', 'desc' => 'Büyük tonajlı gemilerin sevk ve idaresini (kaptanlık), seyir güvenliğini ve gemi operasyonlarını yöneten teknik mühendislik dalıdır.'],
            ['name' => 'Denizcilik İşletmeleri Yönetimi', 'desc' => 'Liman yönetimi, lojistik, gemi kiralama ve deniz ticareti hukuku gibi denizcilik sektörünün iş dünyası ve operasyonel kısmına odaklanır.'],
            ['name' => 'Elektrik Mühendisliği', 'desc' => 'Elektrik enerjisinin üretimi, iletimi, dağıtımı ve yüksek gerilim sistemleri üzerine odaklanan mühendislik dalıdır.'],
            ['name' => 'Elektrik-Elektronik Mühendisliği', 'desc' => 'Elektrik gücünün yanı sıra; devre tasarımı, haberleşme sistemleri, mikroçipler og otomasyon gibi düşük voltajlı sistemleri de kapsayan geniş bir alandır.'],
            ['name' => 'Egzersiz ve Spor Bilimleri', 'desc' => 'Fiziksel aktivitenin insan vücudu üzerindeki etkilerini, sporcu performansını geliştirmeyi ve sağlıklı yaşam için egzersiz programları hazırlamayı bilimsel olarak ele alır.'],
            ['name' => 'Elektronik Mühendisliği', 'desc' => 'Mikroçipler, yarı iletken cihazlar, devre tasarımı ve kontrol sistemleri gibi alçak gerilimli sistemlerin tasarımı ve geliştirilmesine odaklanır.'],
            ['name' => 'Elektronik ve Haberleşme Mühendisliği', 'desc' => 'Elektronik sistemlerin yanı sıra; radyo frekansları, fiber optik, uydu haberleşmesi ve 5G gibi veri iletim teknolojileri üzerine uzmanlaşan daldır.'],
            ['name' => 'Endüstri Mühendisliği', 'desc' => 'İnsan, makine, malzeme ve bilgiden oluşan sistemlerin verimliliğini artırmak için matematiksel modeller ve optimizasyon yöntemleri kullanarak süreçleri yöneten disiplindir.'],
            ['name' => 'Endüstriyel Tasarım Mühendisliği', 'desc' => 'Endüstriyel tasarımın estetik bakış açısını, mühendisliğin üretim teknikleriyle birleştirerek; bir ürünün hem şık hem de seri üretime uygun olmasını sağlayan hibrit alandır.'],
            ['name' => 'Endüstriyel Tasarım', 'desc' => 'Seri üretilecek ürünlerin kullanıcı ihtiyaçlarına uygun olarak estetik, ergonomik ve işlevsel şekilde tasarlanması sürecidir.'],
            ['name' => 'Elektronik Ticaret ve Yönetimi', 'desc' => 'Dijital pazarların işleyişi, online satış stratejileri, dijital pazarlama ve e-ticaret lojistiği konularında uzmanlar yetiştiren yönetim odaklı bölümdür.'],
            ['name' => 'Emlak ve Emlak Yönetimi', 'desc' => 'Gayrimenkul geliştirme, taşınmaz değerleme (ekspertiz), emlak hukuku ve konut yönetimi konularında profesyonel bilgi kazandırır.'],
            ['name' => 'Enerji Sistemleri Mühendisliği', 'desc' => 'Fosil yakıtlardan yenilenebilir kaynaklara kadar tüm enerji türlerinin üretimi, dağıtımı ve enerji verimliliği sağlayan sistemlerin tasarlanmasıyla ilgilenir.'],
            ['name' => 'Enerji Bilimi ve Teknolojileri', 'desc' => 'Enerjinin temel fiziksel ve kimyasal prensiplerine, yeni nesil depolama teknolojilerine ve Ar-Ge çalışmalarına odaklanan daha teorik ve bilim ağırlıklı bölümdür.'],
            ['name' => 'Enerji Yönetimi', 'desc' => 'Enerji sektörünün ekonomi, hukuk, politika ve idari yönetim boyutuna odaklanarak; enerji verimliliği projelerinin yönetimini ve mevzuat takibini üstlenir.'],
            ['name' => 'Ergoterapi (İş ve Uğraşı Terapisi)', 'desc' => 'Herhangi bir hastalık, engel veya yaşlılık nedeniyle günlük yaşam aktivitelerinde kısıtlılık yaşayan bireylerin; toplumsal hayata katılımını ve bağımsızlığını artırmak için tedavi yöntemleri geliştirir.'],
            ['name' => 'Fars Dili og Edebiyatı', 'desc' => 'Farsça dil yapısını, tarihsel gelişimini ve İran kültürünün ürettiği klasik ve modern edebi eserleri akademik düzeyde inceler.'],
            ['name' => 'Farsça Mütercim ve Tercümanlık', 'desc' => 'Farsça ve Türkçe arasında teknik, edebi, siyasi ve diplomatik metinlerin yazılı ve sözlü çevirisini yapabilecek dil uzmanları yetiştirir.'],
            ['name' => 'Felsefe', 'desc' => 'Varlık, bilgi, ahlak, mantık ve siyaset gibi evrensel konuları rasyonel ve eleştirel bir bakış açısıyla sorgulayan, düşünce tarihini ve sistemlerini inceleyen temel disiplindir.'],
            ['name' => 'Felsefe Grubu Öğretmenliği', 'desc' => 'Ortaöğretim düzeyindeki okullarda felsefe, psikoloji, sosyoloji ve mantık derslerini verebilecek, pedagojik formasyona sahip eğitimciler yetiştirir.'],
            ['name' => 'Fen Bilgisi Öğretmenliği', 'desc' => 'Ortaokul düzeyinde temel fizik, kimya ve biyoloji kavramlarını öğrencilere aktaran; doğayı ve bilimsel süreci anlamayı hedefleyen öğretmenlik dalıdır.'],
            ['name' => 'Finans ve Bankacılık', 'desc' => 'Bireylerin ve kurumların para yönetimini, yatırım araçlarını, sermaye piyasalarını ve bankaların operasyonel süreçlerini finansal modeller üzerinden inceleyen daldır.'],
            ['name' => 'Fizik', 'desc' => 'Maddenin yapısını, enerjiyi, kuvvetleri ve evrenin temel yasalarını mikroskobik ölçekten galaktik ölçeğe kadar deneysel ve teorik olarak inceleyen temel bilimdir.'],
            ['name' => 'Fizik Mühendisliği', 'desc' => 'Fizik yasalarını modern teknolojilere، endüstriyel tasarımlara ve mühendislik problemlerine uygulayan; ileri malzeme, nanoteknoloji ve enerji sistemleri üzerinde çalışan disiplindir.'],
            ['name' => 'Fizik Öğretmenliği', 'desc' => 'Lise seviyesindeki fizik müfredatını öğrencilere öğretmek üzere pedagojik ve teknik donanım kazandıran bölümdür.'],
            ['name' => 'Fotonik', 'desc' => 'Işığın üretilmesi, kontrol edilmesi, iletilmesi ve algılanmasıyla ilgilenen; lazer teknolojileri, fiber optik ve optik sensörler üzerine yoğunlaşan ileri teknoloji alanıdır.'],
            ['name' => 'Fizyoterapi ve Rehabilitasyon', 'desc' => 'Yaralanma, hastalık veya yaşlılık nedeniyle hareket kısıtlılığı yaşayan bireylerين fiziksel fonksiyonlarını geliştirmek için egzersiz ve manuel tekniklerle tedavi uygulayan sağlık branşıdır.'],
            ['name' => 'Film Tasarımı ve Yönetimi', 'desc' => 'Senaryo yazımından yönetmenliğe، çekim tekniklerinden kurguya kadar bir sinema eserinin tüm sanatsal ve teknik üretim süreçlerini yöneten uzmanlar yetiştirir.'],
            ['name' => 'Fotoğraf ve Video', 'desc' => 'Durağan ve hareketli görüntülerin teknik ve sanatsal boyutunu kullanarak dijital içerik üretimi، reklamcılık veya sanat alanında uzmanlaşan bölümdür.'],
            ['name' => 'Fransız Dili og Edebiyatı', 'desc' => 'Fransızca dilinin yapısını, tarihsel değişimini ve Fransız kültürünün dünya edebiyatına yön veren eserlerini akademik ve eleştirel bir bakış açısıyla inceler.'],
            ['name' => 'Fransızca Mütercim ve Tercümanlık', 'desc' => 'Fransızca ve Türkçe dilleri arasında; yazılı metinlerin çevirisi ve sözlü iletişim süreçlerinde profesyonel düzeyde köprü kuracak uzmanlar yetiştirir.'],
            ['name' => 'Fransızca Öğretmenliği', 'desc' => 'Fransızca dilini هر yaş grubuna etkili yöntemlerle öğretmek üzere; dil yetkinliği, sınıf yönetimi ve eğitim psikolojisi üzerine uzmanlık kazandırır.'],
            ['name' => 'Gastronomi ve Mutfak Sanatları', 'desc' => 'Yemek pişirme tekniklerini، gıda bilimini ve mutfak yönetimini birleştiren; yemek kültürünü sanatsal bir estetik ve profesyonel işletmecilik anlayışıyla ele alan bölümdür.'],
            ['name' => 'Gazetecilik', 'desc' => 'Güncel olayları araştırma، haber değeri taşıyan içerikleri toplama، yazma ve dijital/yazılı medya kanalları aracılığıyla topluma etik kurallar çerçevesinde aktarma sürecidir.'],
            ['name' => 'Geleneksel Türk Sanatları', 'desc' => 'Hat, ebru, tezhip, çini, halı-kilim dokuma gibi köklü Türk kültür mirasına dayalı sanat dallarının tekniklerini öğreten ve bu değerleri modern tasarımlarla geleceğe taşıyan alandır.'],
            ['name' => 'Gayrimenkul Geliştirme ve Yönetimi', 'desc' => 'Arazi ve konut projelerinin finansal analizi، taşınmaz değerleme، gayrimenkul hukuku ve yatırım stratejileri üzerine odaklanan، ekonomi ve işletme temelli bir bölümdür.'],
            ['name' => 'Gemi İnşaatı ve Gemi Makineleri Mühendisliği', 'desc' => 'Her türlü deniz taşıtının tasarımı، gövde yapısı، stabilite hesapları ve içindeki makine sistemlerinin montajı/bakımı üzerine uzmanlaşan teknik mühendislik dalıdır.'],
            ['name' => 'Gemi Makineleri İşletme Mühendisliği', 'desc' => 'Gemilerin ana makinelerinin، yardımcı sistemlerinin ve elektrik devrelerinin çalıştırılması، bakımı ve onarımıyla ilgilenen uzmanlar yetiştiren bölümdür.'],
            ['name' => 'Gemi ve Deniz Teknolojisi Mühendisliği', 'desc' => 'Gemi inşaatının yanı sıra deniz altı yapıları، açık deniz platformları ve yenilenebilir deniz enerji sistemlerinin tasarımı ve üretimi üzerine uzmanlaşan mühendislik dalıdır.'],
            ['name' => 'Gemi ve Yat Tasarımı', 'desc' => 'Deniz araçlarının hem estetik görünümünü hem de iç mekan fonksiyonelliğini، mühendislik sınırları içerisinde tasarlayan sanat ve teknik odaklı bölümdür.'],
            ['name' => 'Genetik ve Biyomühendislik', 'desc' => 'Canlıların genetik yapısını analiz eden ve bu bilgileri mühendislik teknikleriyle birleştirerek yeni tedavi yöntemleri، ilaçlar veya tarımsal ürünler geliştiren bilim dalıdır.'],
            ['name' => 'Geomatik Mühendisliği (Harita Mühendisliği)', 'desc' => 'Yeryüzünün ölçülmesi، uydu görüntüleri ve GPS verileriyle haritalandırılması، coğrafi bilgi sistemlerinin yönetilmesi ve arazi planlaması süreçlerini kapsار.'],
            ['name' => 'Gerontoloji (Yaşlılık Bilimi)', 'desc' => 'Yaşlanmanın biyolojik، psikolojik ve sosyal boyutlarını inceleyen; yaşlı bireylerin yaşam kalitesini artıracak politikalar ve bakım modelleri geliştiren bilim dalıdır.'],
            ['name' => 'Gıda Mühendisliği', 'desc' => 'Tarımsal hammaddelerin güvenli، kaliteli ve uzun ömürlü gıda ürünlerine dönüştürülmesi için üretim süreçlerini، paketleme ve depolama tekniklerini tasarlayan daldır.'],
            ['name' => 'Görsel İletişim Tasarımı', 'desc' => 'Bilgiyi ve mesajı dijital mecralarda etkili bir şekilde aktarmak için grafik، tipografi ve etkileşimli öğeleri birleştiren tasarım dalıdır.'],
            ['name' => 'Görsel Sanatlar', 'desc' => 'Resim, heykel, seramik gibi geleneksel sanat dallarının yanı sıra modern sanat pratiklerini ve teorilerini kapsayan، yaratıcı ifadeye odaklanan bölümdür.'],
            ['name' => 'Grafik Tasarımı', 'desc' => 'Logo, afiş, kitap tasarımı gibi görsel unsurların; bir marka kimliği oluşturmak veya bir mesajı görsel yolla iletmek amacıyla estetik ve teknik kurallarla düzenlenmesi sanatıdır.'],
            ['name' => 'Halkla İlişkiler ve Reklamcılık', 'desc' => 'Bir kurumun veya markanın itibarını yönetme، hedef kitleyle stratejik iletişim kurma ve ürün/hizmetleri tanıtmak için yaratıcı kampanyalar yürütme alanıdır.'],
            ['name' => 'Girişimcilik', 'desc' => 'Yeni iş fikirleri geliştirme، risk yönetimi، pazar analizi ve yenilikçi iş modelleri kurma süreçlerini öğreterek liderler yetiştirir.'],
            ['name' => 'Gümrük İşletme', 'desc' => 'Uluslararası ticaret hukukuna uygun olarak malların gümrüklerden geçiş işlemlerini، vergilendirme süreçlerini ve dış ticaret lojistiğini yöneten uzmanlık alanıdır.'],
            ['name' => 'Halkla İlişkiler ve Tanıtım', 'desc' => 'Bir kurum veya markanın kamuoyundaki imajını yöneten، hedef kitleyle stratejik iletişim kuran ve tanıtım faaliyetlerini organize eden bölümdür.'],
            ['name' => 'Havacılık Elektrik ve Elektroniği', 'desc' => 'Hava araçlarının uçuş kontrol، seyrüsefer، haberleşme ve güç sistemleri gibi elektronik aksamlarının bakımı ve tasarımı üzerine odaklanır.'],
            ['name' => 'Havacılık ve Uzay Mühendisliği', 'desc' => 'Uçak، helikopter gibi hava araçları ile uydu ve roket gibi uzay araçlarının tasarımını، üretimini ve test süreçlerini yöneten mühendislik dalıdır.'],
            ['name' => 'Havacılık Yönetimi', 'desc' => 'Havayolu şirketleri ve havalimanlarının işletilmesi، uçuş planlaması، lojistik ve sivil havacılık operasyonlarının idari süreçlerini konu alır.'],
            ['name' => 'Hayvansal Üretim ve Teknolojileri', 'desc' => 'Büyükbaş، küçükbaş ve kümes hayvanlarının ıslahı، beslenmesi ve hayvansal ürünlerin verimli şekilde elde edilmesi için modern teknolojiler geliştiren alandır.'],
            ['name' => 'Hemşirelik', 'desc' => 'Bireylerin sağlığını koruma، hastalık sürecinde tıbbi bakım sağlama ve doktor tarafından planlanan tedavileri uygulama üzerine uzmanlaşan sağlık bilimidir.'],
            ['name' => 'Hidrojeoloji Mühendisliği', 'desc' => 'Yer altı sularının oluşumu، hareketi، kalitesi ve bu kaynakların çevreyle olan etkileşimini mühendislik yöntemleriyle inceleyen daldır.'],
            ['name' => 'Hukuk', 'desc' => 'Adalet sistemini، toplumsal düzeni sağlayan yasaları، bu yasaların uygulanmasını ve bireyler/kurumlar arasındaki hukuki uyuşmazlıkların çözümünü inceleyen disiplindir.'],
            ['name' => 'İç Mimarlık', 'desc' => 'Bina içindeki mekanların estetik، işlevsel ve kullanıcı ihtiyaçlarına uygun şekilde tasarlanması ve dekorasyon süreçlerini yöneten bölümdür.'],
            ['name' => 'İç Mimarlık ve Çevre Tasarımı', 'desc' => 'Mekan tasarımını fiziksel çevreyle bütünleştiren; malzeme، aydınlatma ve kullanıcı konforunu çevresel bağlamıyla birlikte ele alan uzmanlık alanıdır.'],
            ['name' => 'İlahiyat', 'desc' => 'İslam dininin temel kaynaklarını، inanç sistemini، tarihini ve dini bilimleri akademik bir perspektifle araştıran ve inceleyen bölümdür.'],
            ['name' => 'İletişim', 'desc' => 'Bilgi، duygu ve düşüncelerin farklı kanallar aracılığıyla hedef kitleye aktارılması süreçlerini kapsayan geniş bir alandır.'],
            ['name' => 'İletişim Bilimleri', 'desc' => 'İletişim süreçlerinin toplumsal، psikolojik ve kültürel etkilerini teorik modeller ve araştırmalar üzerinden inceleyen akademik disiplindir.'],
            ['name' => 'İletişim Sanatları', 'desc' => 'Reklamcılık، halkla ilişkiler ve görsel sanatları birleştirerek، markalar veya kurumlar için yaratıcı iletişim stratejileri ve içerikleri geliştiren bölümdür.'],
            ['name' => 'İletişim Tasarımı ve Yönetimi', 'desc' => 'Tasarım odaklı düşünmeyi، kurumsal iletişim stratejileri ve medya projelerinin yönetim süreçleriyle birleştiren disiplindir.'],
            ['name' => 'İletişim ve Tasarımı', 'desc' => 'Bir mesajın dijital ve görsel platformlarda en etkili ve estetik şekilde sunulması için gerekli teknik ve teorik altyapıyı sağlar.'],
            ['name' => 'İlköğretim Matematik Öğretmenliği', 'desc' => 'Ortaokul düzeyindeki öğrencilere temel matematik kavramlarını öğretecek، pedagojik formasyon eğitimi almış öğretmenler yetiştirir.'],
            ['name' => 'İmalat Mühendisliği', 'desc' => 'Ürünlerin hammaddeden son mamule dönüştüğü üretim sistemlerini، fabrikalardaki makineleri og otomasyon süreçlerini tasarlayan teknik daldır.'],
            ['name' => 'İngiliz Dilbilimi', 'desc' => 'İngilizcenin yapısını، ses dizilimini، cümle kuruluşlarını، dilin tarihsel gelişimini ve anlam bilimini bilimsel yöntemlerle inceleyen uzmanlık alanıdır.'],
            ['name' => 'İngiliz Dili og Edebiyatı', 'desc' => 'İngiliz kültürüne ait klasik ve modern edebi eserleri analiz ederek، eleştirel düşünme ve ileri düzey akademik dil yetkinliği kazandırır.'],
            ['name' => 'İngilizce Mütercim ve Tercümanlık', 'desc' => 'İngilizce ve Türkçe dilleri arasında; hukuki، tıbbi، teknik metinlerin yazılı çevirisi ile her türlü toplantıda anlık çeviri yapabilecek profesyoneller yetiştirir.'],
            ['name' => 'İngilizce Öğretmenliği', 'desc' => 'İngilizceyi yabancı dil olarak öğretecek; dil öğretim metodolojileri og sınıf yönetimi konusunda uzmanlaşmış eğitimciler yetiştirir.'],
            ['name' => 'İnşaat Mühendisliği', 'desc' => 'Bina, köprü, baraj, yol gibi yapıların statik hesaplarını yapan، tasarımını hazırlayan ve inşaat süreçlerini denetleyen temel mühendislik dalıdır.'],
            ['name' => 'İnsan Kaynakları Yönetimi', 'desc' => 'Bir kurumdaki personelin işe alımı، eğitimi، performans değerlendirmesi ve motivasyonu gibi süreçleri stratejik olarak yöneten alandır.'],
            ['name' => 'İş Sağlığı ve Güvenliği', 'desc' => 'Çalışma ortamlarında meydana gelebilecek iş kazalarını ve meslek hastalıklarını önlemek amacıyla risk analizi yapan ve güvenlik önlemleri planlayan disiplindir.'],
            ['name' => 'İslam İktisadı ve Finans', 'desc' => 'İslami prensiplere dayalı ekonomi modellerini، faizsiz bankacılık sistemlerini ve katılım finansı yöntemlerini modern iktisat kuramlarıyla birlikte inceleyen bölümdür.'],
            ['name' => 'İslami İlimler', 'desc' => 'Tefsir, hadis, fıkıh ve kelam gibi temel İslam bilimlerini akademik bir perspektifle araştıran disiplindir.'],
            ['name' => 'İşletme', 'desc' => 'Bir kurumun verimli çalışabilmesi için gerekli olan yönetim، pazarlama، finans، muhasebe ve insan kaynakları süreçlerini planlayan ve yöneten alandır.'],
            ['name' => 'İşletme Mühendisliği', 'desc' => 'Mühendislik bakış açısını işletme yönetimiyle birleştiren; karmaşık sistemlerin verimliliğini artırmak için matematiksel modelleme ve teknik analiz kullanan disiplindir.'],
            ['name' => 'İspanyol Dili ve Edebiyatı', 'desc' => 'İspanyolca dil yapısını, tarihini ve İspanyol kültürünün dünya çapındaki edebi eserlerini inceleyerek ileri düzey dil ve analiz yetkinliği kazandırır.'],
            ['name' => 'İstatistik', 'desc' => 'Verilerin toplanması, analiz edilmesi, yorumlanması ve olasılık hesapları üzerinden geleceğe yönelik anlamlı tahminler yapılmasını sağlayan matematik temelli bilimdir.'],
            ['name' => 'İstatistik ve Bilgisayar Bilimleri', 'desc' => 'Veri analizi yöntemlerini bilgisayar programlama ve yazılım teknolojileriyle birleştirerek, büyük veri setlerini işleme ve dijital çözümler üretme üzerine yoğunlaşan alandır.'],
            ['name' => 'İtalyan Dili ve Edebiyatı', 'desc' => 'İtalyan dilinin gelişimini, gramer yapısını ve İtalyan edebiyatının klasik ve modern dönem eserlerini kültürel bağlamıyla birlikte ele alan bölümdür.'],
            ['name' => 'Japon Dili ve Edebiyatı', 'desc' => 'Japonca dil yetkinliği kazandırmanın yanı sıra, Japonya’nın zengin kültürünü, tarihini ve edebi mirasını akademik bir bakışla inceler.'],
            ['name' => 'Japonca Mütercim ve Tercümanlık', 'desc' => 'Japonca ve Türkçe arasında her türlü yazılı metin ve sözlü iletişimde (toplantı, konferans vb.) profesyonel çeviri yapabilecek uzmanlar yetiştirir.'],
            ['name' => 'Japonca Öğretmenliği', 'desc' => 'Japonca dilini yabancı bir dil olarak öğretmek için gerekli olan pedagojik formasyonu, öğretim tekniklerini ve dil bilgisini kazandıran bölümdür.'],
            ['name' => 'Jeofizik Mühendisliği', 'desc' => 'Fiziğin temel ilkelerini kullanarak yerin fiziksel yapısını, depremleri, yer altı kaynaklarını ve yeryüzündeki fiziksel değişimleri inceleyen mühendislik dalıdır.'],
            ['name' => 'Jeoloji Mühendisliği', 'desc' => 'Yerkürenin katı maddelerini (kayalar, mineraller), yapısını, tarihini ve yer altı kaynaklarının (maden, su, petrol) tespiti ile inşaat zeminlerini araştıran daldır.'],
            ['name' => 'Kamu Yönetimi', 'desc' => 'Devlet kurumlarının işleyişini, siyaset bilimini, yönetim hukukunu ve kamu politikalarının oluşturulması ile uygulanması süreçlerini inceleyen disiplindir.'],
            ['name' => 'Karşılaştırmalı Edebiyat', 'desc' => 'Farklı dillerde ve kültürlerde yazılmış edebi eserlerin birbirleriyle olan ilişkilerini, benzerliklerini ve farklılıklarını tematik veya yapısal olarak inceleyen disiplindir.'],
            ['name' => 'Kentsel Tasarım ve Peyzaj Mimarlığı', 'desc' => 'Şehirlerdeki açık alanların, parkların ve bahçelerin estetik, işlevsel ve ekolojik dengeler gözetilerek planlanması ve tasarlanması süreçlerini kapsar.'],
            ['name' => 'Kimya', 'desc' => 'Maddenin yapısını, özelliklerini, bileşimini ve geçirdiği değişimleri laboratuvar ortamında deney ve gözlemlerle inceleyen temel bilim dalıdır.'],
            ['name' => 'Kimya Mühendisliği', 'desc' => 'Kimyasal süreçleri kullanarak hammaddelerin endüstriyel ölçekte, ekonomik ve güvenli bir şekilde faydalı ürünlere dönüştürülmesini sağlayan mühendislik dalıdır.'],
            ['name' => 'Kimya Öğretmenliği', 'desc' => 'Lise düzeyindeki kimya müfredatını öğrencilere pedagojik yöntemlerle öğretecek, teorik ve laboratuvar bilgisine sahip eğitimciler yetiştirir.'],
            ['name' => 'Kimya-Biyoloji Mühendisliği', 'desc' => 'Kimyasal mühendislik prensiplerini biyolojik sistemlerle birleştirerek ilaç, gıda, energy ve tıp gibi alanlarda biyoteknolojik çözümler üreten disiplindir.'],
            ['name' => 'Kontrol ve Otomasyon Mühendisliği', 'desc' => 'Elektrik, mekanik ve yazılım sistemlerini birleştirerek endüstriyel üretim süreçlerinin veya robotik sistemlerin insan müdahalesi olmadan (otomatik) çalışmasını sağlayan teknolojiler geliştirir.'],
            ['name' => 'Kore Dili ve Edebiyatı', 'desc' => 'Korece dil yetkinliği kazandırmanın yanı sıra; Kore’nin tarihini, kültürünü ve edebi eserlerini akademik bir bakış açısıyla inceler.'],
            ['name' => 'Kültür Varlıklarını Koruma ve Onarım', 'desc' => 'Tarihi eserlerin, yapıların ve belgelerin zamanla bozulmasını önlemek amacıyla bilimsel analizler yaparak onları aslına uygun şekilde restore eden uzmanlık alanıdır.'],
            ['name' => 'Kurgu, Ses ve Görüntü Yönetimi', 'desc' => 'Sinema, televizyon ve dijital medya yapımlarında görüntülerin düzenlenmesi (montaj), ses tasarımı ve çekim süreçlerinin teknik ve sanatsal yönetimini kapsar.'],
            ['name' => 'Kürt Dili ve Edebiyatı', 'desc' => 'Kürtçe dilinin gramer yapısını, lehçelerini, tarihsel gelişimini ve Kürt edebiyatına ait eserleri akademik düzeyde araştıran bölümdür.'],
            ['name' => 'Lojistik Yönetimi', 'desc' => 'Ürünlerin, hizmetlerin ve bilgilerin üretim noktasından tüketim noktasına kadar olan akışını; nakliye, depolama ve gümrükleme süreçleriyle birlikte planlayan yönetim dalıdır.'],
            ['name' => 'Maden Mühendisliği', 'desc' => 'Yer altındaki maden ve mineral kaynaklarının tespiti, çıkarılması, zenginleştirilmesi ve bu süreçlerin iş güvenliği ile çevre kurallarına uygun yönetilmesini sağlayan mühendisliktir.'],
            ['name' => 'Makine Mühendisliği', 'desc' => 'Enerji, kuvvet ve hareket prensiplerini kullanarak her türlü mekanik sistemin, motorun ve makinenin tasarımı, analizi ve üretimini gerçekleştiren temel mühendislik dalıdır.'],
            ['name' => 'Maliye', 'desc' => 'Devletin gelir (vergi) ve harcamalarını, kamu bütçesini ve bu süreçlerin ekonomik ve toplumsal hayata etkilerini inceleyen, ekonomi ve hukuk ağırlıklı disiplindir.'],
            ['name' => 'Malzeme Bilimi ve Mühendisliği', 'desc' => 'Metaller, seramikler, polimerler ve kompozitlerin atomik yapılarını inceleyerek endüstrinin ihtiyaçlarına yönelik yeni ve dayanıklı malzemeler geliştiren alandır.'],
            ['name' => 'Malzeme Bilimi ve Nanoteknoloji Mühendisliği', 'desc' => 'Maddeyi atomik ve moleküler (nano) düzeyde kontrol ederek; savunma, sağlık ve elektronik gibi alanlar için üstün özelliklere sahip ileri teknoloji malzemeleri tasarlayan daldır.'],
            ['name' => 'Matematik', 'desc' => 'Sayılar, yapılar, şekiller ve değişimler arasındaki mantıksal ilişkileri inceleyen; evrenin işleyişini anlamaya yarayan teorik ve uygulamalı temel bilimdir.'],
            ['name' => 'Matematik Mühendisliği', 'desc' => 'Karmaşık mühendislik ve endüstri problemlerini çözmek için matematiksel modeller kuran, algoritmalar geliştiren ve bu modelleri bilgisayar sistemlerine uyarlayan disiplindir.'],
            ['name' => 'Matematik Öğretmenliği', 'desc' => 'Lise müfredatındaki matematik konularını (geometri, cebir, analiz vb.) öğrencilere pedagojik yöntemlerle öğretecek profesyonel eğitimciler yetiştirir.'],
            ['name' => 'Matematik ve Bilgisayar Bilimleri', 'desc' => 'Matematiğin teorik mantığını bilgisayar yazılımı ve algoritma geliştirme süreçleriyle birleştirerek veri bilimi ve yapay zeka gibi alanlarda çözümler üreten bölümdür.'],
            ['name' => 'Medya ve Görsel Sanatlar', 'desc' => 'Sinema, video, grafik tasarım ve dijital sanatlar gibi alanlarda yaratıcı içerikler üretmeyi ve bu içeriklerin estetik/toplumsal boyutunu incelemeyi amaçlar.'],
            ['name' => 'Medya ve İletişim', 'desc' => 'Geleneksel ve dijital medya araçları üzerinden bilgi ve haber üretimi, yayıncılık yönetimi ve medyanın toplum üzerindeki etkilerini analiz eden alandır.'],
            ['name' => 'Mekatronik Mühendisliği', 'desc' => 'Makine, elektrik-elektronik ve bilgisayar mühendisliğinin kesişim noktasında yer alan; robotlar, akıllı makineler ve otomasyon sistemleri geliştiren hibrit disiplindir.'],
            ['name' => 'Metalurji ve Malzeme Mühendisliği', 'desc' => 'Özellikle metallerin ve alaşımların ham maddeden son ürüne dönüştürülmesini, işlenmesini ve bu malzemelerin fiziksel/kimyasal özelliklerini inceleyen mühendislik dalıdır.'],
            ['name' => 'Meteoroloji Mühendisliği', 'desc' => 'Atmosferdeki hava olaylarını, iklim değişikliğini ve hava tahminlerini matematiksel/fiziksel modellerle analiz eden, yenilenebilir enerji ve havacılık gibi sektörlere veri sağlayan mühendislik dalıdır.'],
            ['name' => 'Mimarlık', 'desc' => 'İnsanların barınma ve çalışma gibi ihtiyaçlarına yönelik estetik, işlevsel, güvenli ve sürdürülebilir yapılar tasarlayan, bu yapıların inşa süreçlerini koordine eden disiplindir.'],
            ['name' => 'Moda Tasarımı', 'desc' => 'Giyim ve aksesuarlar için estetik, malzeme ve pazar trendlerini harmanlayarak yeni koleksiyonlar oluşturan, çizimden üretime kadar olan süreci yöneten yaratıcı alandır.'],
            ['name' => 'Moleküler Biyoloji ve Genetik', 'desc' => 'Canlı organizmaları moleküler düzeyde inceleyerek genlerin yapısını, işleyişini ve kalıtım mekanizmalarını araştıran, hastalıkların teşhis ve tedavisinde temel bilimsel veriler üreten daldır.'],
            ['name' => 'Moleküler Biyoteknoloji', 'desc' => 'Canlı sistemleri moleküler düzeyde manipüle ederek tıp, tarım ve endüstri alanında yeni ilaçlar, aşılar veya genetiği geliştirilmiş ürünler tasarlayan uygulama alanıdır.'],
            ['name' => 'Muhasebe ve Finans Yönetimi', 'desc' => 'Kurumların tüm mali kayıtlarını tutan, bütçe planlaması yapan ve şirketin finansal sağlığını korumak için yatırım ve risk analizleri gerçekleştiren yönetim disiplinidir.'],
            ['name' => 'Mütercim-Tercümanlık', 'desc' => 'İki veya daha fazla dil arasında yazılı metinlerin çevirisini veya sözlü (simültane/ardıl) iletişimi profesyonel düzeyde gerçekleştirerek kültürler arası köprü kuran uzmanlık alanıdır.'],
            ['name' => 'Nükleer Enerji Mühendisliği', 'desc' => 'Atom çekirdeğinin enerjisinden yararlanarak elektrik üretimi sağlayan nükleer santrallerin tasarımı, işletilmesi, radyasyon güvenliği ve nükleer atık yönetimi üzerine çalışan mühendisliktir.'],
            ['name' => 'Odyoloji', 'desc' => 'İşitme ve denge bozukluklarının önlenmesi, teşhis edilmesi ve bu sorunların rehabilitasyonu için işitme cihazı veya terapi yöntemlerinin uygulanması üzerine uzmanlaşan sağlık dalıdır.'],
            ['name' => 'Okul Öncesi Öğretmenliği', 'desc' => '0-6 yaş grubu çocukların fiziksel, zihinsel ve sosyal gelişimlerini destekleyen, onları temel eğitim dönemine hazırlayan pedagoji ve eğitim dalıdır.'],
            ['name' => 'Optik ve Akustik Mühendisliği', 'desc' => 'Işığın ve sesin kontrol edilmesi, iletilmesi ve ölçülmesi üzerine teknolojiler geliştiren; lazer sistemleri, görüntüleme teknolojileri veya ses yalıtımı gibi alanlarda uzmanlaşan daldır.'],
            ['name' => 'Orman Mühendisliği', 'desc' => 'Orman kaynaklarının sürdürülebilir şekilde yönetilmesi, korunması, ağaçlandırılması ve ekosistemin dengesini bozmadan ekonomik olarak değerlendirilmesi süreçlerini yöneten disiplindir.'],
            ['name' => 'Ortez ve Protez', 'desc' => 'Eksik uzuvların yerine yapay araçlar (protez) tasarlayan veya kas-iskelet sistemi bozukluklarını destekleyici cihazlarla (ortez) tedavi eden sağlık teknolojisi alanıdır.'],
            ['name' => 'Otel Yöneticiliği', 'desc' => 'Konaklama tesislerinin operasyonel süreçlerini, müşteri hizmetlerini, personel yönetimini ve işletme karlılığını koordine eden turizm odaklı yönetim bölümüdür.'],
            ['name' => 'Otomotiv Mühendisliği', 'desc' => 'Kara taşıtlarının (otomobil, kamyon, otobüs vb.) tasarımı, motor sistemleri, şasi yapısı ve üretim teknolojileri üzerine uzmanlaşan mekanik ağırlıklı mühendislik dalıdır.'],
            ['name' => 'Özel Eğitim Öğretmenliği', 'desc' => 'Zihinsel, fiziksel veya duygusal açıdan özel gereksinimi olan bireylere, onların öğrenme hızına ve ihtiyaçlarına uygun tekniklerle eğitim veren profesyonel branştır.'],
            ['name' => 'Pazarlama', 'desc' => 'Ürün veya hizmetlerin hedef kitleye ulaştırılması için pazar analizi yapan, reklam, markalaşma ve satış stratejileri geliştirerek değer yaratan iş dünyası disiplinidir.'],
            ['name' => 'Perfüzyon', 'desc' => 'Kalp ve akciğer ameliyatları sırasında vücudun kan dolaşımını ve oksijenlenmesini sağlayan "yapay kalp-akciğer makinesini" ameliyat esnasında yöneten tıbbi uzmanlık dalıdır.'],
            ['name' => 'Petrol ve Doğalgaz Mühendisliği', 'desc' => 'Yer altındaki hidrokarbon kaynaklarının (petrol, gaz) tespiti, sondaj yöntemleriyle çıkarılması ve rafine edilmesi süreçlerini teknik ve ekonomik olarak yöneten mühendisliktir.'],
            ['name' => 'Peyzaj Mimarlığı', 'desc' => 'Parklar, bahçeler ve kentsel açık alanlar gibi dış mekanların estetik, ekolojik ve toplumsal ihtiyaçlara göre bitkilendirme ve yapısal planlamasını yapan mimari daldır.'],
            ['name' => 'Pilotaj', 'desc' => 'Hava araçlarının teknik donanımı, hava hukuku, meteoroloji ve seyir kuralları üzerine eğitim vererek profesyonel ticari pilotlar yetiştiren bölümdür.'],
            ['name' => 'Polimer Malzeme Mühendisliği', 'desc' => 'Plastik, kauçuk ve fiber gibi polimer yapıdaki malzemelerin kimyasal sentezi, işlenmesi ve yeni ürünlere dönüştürülmesi üzerine odaklanan mühendislik dalıdır.'],
            ['name' => 'Psikoloji', 'desc' => 'İnsan davranışlarını, zihinsel süreçleri, duyguları ve bunların altında yatan biyolojik/sosyal nedenleri bilimsel yöntemlerle inceleyen temel bilim dalıdır.'],
            ['name' => 'Psikolojik Danışmanlık ve Rehberlik (PDR)', 'desc' => 'Bireylerin kişisel, sosyal, eğitsel ve mesleki gelişimlerini desteklemek ve sorunlarıyla başa çıkma becerisi kazandırmak amacıyla rehberlik hizmeti sunan alandır.'],
            ['name' => 'Radyo, Televizyon ve Sinema', 'desc' => 'Medya içeriklerinin üretim süreçlerini, kamera arkası tekniklerini, senaryo yazımını, kurguyu ve yayıncılık kuramlarını kapsayan disiplindir.'],
            ['name' => 'Raylı Sistemler Mühendisliği', 'desc' => 'Tren, metro ve tramvay gibi raylı ulaşım araçlarının tasarımı, ray inşası, sinyalizasyon ve elektrifikasyon sistemleri üzerine uzmanlaşan mühendislik dalıdır.'],
            ['name' => 'Reklamcılık', 'desc' => 'Bir ürünün, hizmetin veya fikrin hedef kitleye tanıtılması için ikna edici stratejiler, yaratıcı içerikler ve medya planları geliştiren iletişim dalıdır.'],
            ['name' => 'Rekreasyon Yönetimi', 'desc' => 'İnsanların boş zamanlarını değerlendirmesi için eğlence, spor, turizm ve kültürel faaliyetleri planlayan, organize eden ve yöneten profesyonel alandır.'],
            ['name' => 'Rus Dili ve Edebiyatı', 'desc' => 'Rusça dil yapısını, tarihini ve Rus kültürünün ürettiği edebi eserleri dilbilimsel ve eleştirel bir bakış açısıyla akademik düzeyde inceler.'],
            ['name' => 'Rusça Mütercim ve Tercümanlık', 'desc' => 'Rusça ve Türkçe dilleri arasında profesyonel düzeyde yazılı metin çevirisi ve sözlü (anlık/ardıl) iletişim aracılığı yapan uzmanlık alanıdır.'],
            ['name' => 'Sağlık Yönetimi', 'desc' => 'Hastanelerin ve sağlık kuruluşlarının finansal, idari, insan kaynakları ve operasyonel süreçlerini verimli bir şekilde yönetebilecek yöneticiler yetiştirir.'],
            ['name' => 'Sanat Tarihi', 'desc' => 'İlk çağlardan günümüze kadar üretilen mimari yapıları, resim, heykel ve diğer görsel sanat eserlerini tarihsel, kültürel ve estetik bağlamıyla inceleyen bölümdür.'],
            ['name' => 'Şehir ve Bölge Planlama', 'desc' => 'Kentlerin ve bölgelerin fiziksel, sosyal ve ekonomik gelişimini düzenleyen; yaşanabilir, estetik ve sürdürülebilir yerleşim alanları tasarlayan disiplindir.'],
            ['name' => 'Sermaye Piyasası', 'desc' => 'Hisse senedi, tahvil gibi finansal araçların alım satımı, borsa işleyişi, yatırım analizi ve portföy yönetimi üzerine odaklanan finans dalıdır.'],
            ['name' => 'Seyahat İşletmeciliği', 'desc' => 'Turizm acenteleri ve tur operatörlerinin yönetimi, tur planlaması, biletleme ve seyahat organizasyonları üzerine eğitim veren bölümdür.'],
            ['name' => 'Sigortacılık ve Risk Yönetimi', 'desc' => 'Bireysel ve kurumsal riskleri analiz eden, bu risklerin olası finansal zararlarını karşılayacak sigorta poliçelerini ve güvence sistemlerini yöneten daldır.'],
            ['name' => 'Sınıf Öğretmenliği', 'desc' => 'İlkokul (1-4. sınıf) düzeyindeki çocukların temel eğitim süreçlerini yöneten, okuma-yazma ve temel bilimler eğitimini pedagojik yöntemlerle veren branştır.'],
            ['name' => 'Siyasal Bilimler', 'desc' => 'İktidar, otorite, devlet yapıları ve siyasal düşüncelerin doğasını, tarihini ve işleyişini kuramsal ve ampirik olarak inceleyen bilimdir.'],
            ['name' => 'Siyaset Bilimi ve Kamu Yönetimi', 'desc' => 'Devletin yapısını, siyasal kurumları, yerel yönetimleri ve kamu politikalarının oluşturulup uygulanma süreçlerini inceleyen disiplindir.'],
            ['name' => 'Siyaset Bilimi ve Uluslararası İlişkiler', 'desc' => 'Devletler arası siyasi, ekonomik ve hukuki ilişkileri, küresel örgütleri ve dünya politikasını analiz eden uzmanlık dalıdır.'],
            ['name' => 'Sosyal Bilgiler Öğretmenliği', 'desc' => 'Ortaokul seviyesinde tarih, coğrafya, vatandaşlık ve hukuk gibi toplumsal konuları öğrencilere pedagojik yöntemlerle aktaran öğretmenlik dalıdır.'],
            ['name' => 'Sosyal Hizmet', 'desc' => 'Toplumdaki dezavantajlı grupların (çocuklar, yaşlılar, engelliler vb.) yaşam kalitesini artırmak için sosyal destek sistemleri ve politikalar geliştiren uygulama alanıdır.'],
            ['name' => 'Sosyoloji', 'desc' => 'Toplumun yapısını, değişimini, toplumsal grupları, kurumları ve insanlar arasındaki sosyal etkileşimleri bilimsel yöntemlerle inceleyen temel bilimdir.'],
            ['name' => 'Spor Yöneticiliği', 'desc' => 'Spor kulüpleri, tesisleri ve organizasyonlarının idari, mali ve operasyonel süreçlerini yönetebilecek profesyoneller yetiştiren daldır.'],
            ['name' => 'Su Ürünleri Mühendisliği', 'desc' => 'Deniz ve iç sulardaki canlıların üretimi, avlanması, işlenmesi ve su kaynaklarının korunması üzerine uzmanlaşan mühendislik dalıdır.'],
            ['name' => 'Takı Tasarımı', 'desc' => 'Değerli metaller ve taşları kullanarak estetik, özgün ve teknik açıdan uygulanabilir takı ve aksesuarlar tasarlayıp üretmeyi öğreten sanat dalıdır.'],
            ['name' => 'Tapu Kadastro', 'desc' => 'Taşınmaz malların hukuki durumunu belirleyen kayıtların tutulması, sınır tespiti (haritalandırma) ve mülkiyet işlemlerinin yönetimini kapsayan bölümdür.'],
            ['name' => 'Tarih', 'desc' => 'Geçmişteki insan topluluklarının faaliyetlerini, kültürlerini ve olaylar arasındaki neden-sonuç ilişkilerini belgeler ışığında inceleyen temel bilimdir.'],
            ['name' => 'Tarih Öğretmenliği', 'desc' => 'Tarih biliminin temel konularını lise düzeyindeki öğrencilere aktarmak üzere pedagojik ve bilimsel donanım kazandıran öğretmenlik branşıdır.'],
            ['name' => 'Tarım Ekonomisi', 'desc' => 'Tarımsal üretimin planlanması, verimlilik analizi, tarım ürünlerinin pazarlanması ve kırsal kalkınma politikaları üzerine yoğunlaşan disiplindir.'],
            ['name' => 'Tarım Makineleri ve Teknolojileri Mühendisliği', 'desc' => 'Tarımsal faaliyetlerde kullanılan makinelerin tasarımı, üretimi ve akıllı tarım teknolojilerinin sisteme entegrasyonu ile ilgilenen mühendisliktir.'],
            ['name' => 'Tarla Bitkileri', 'desc' => 'Tahıllar, baklagiller ve endüstri bitkilerinin yetiştirilmesi, ıslah edilmesi ve verimliliğinin artırılması üzerine bilimsel çalışmalar yürüten uzmanlık alanıdır.'],
            ['name' => 'Tekstil Mühendisliği', 'desc' => 'Lif, iplik ve kumaş üretim süreçlerini, tekstil kimyasını ve bu ürünlerin endüstriyel boyutta imalat teknolojilerini konu alan mühendislik dalıdır.'],
            ['name' => 'Tekstil ve Moda Tasarımı', 'desc' => 'Kumaş yapısından giysi formuna kadar tekstil ürünlerini estetik ve trendlere uygun şekilde tasarlayan yaratıcı bir disiplindir.'],
            ['name' => 'Tıp', 'desc' => 'İnsan sağlığının korunması, hastalıkların teşhisi, tedavisi ve cerrahi müdahaleler konusunda en üst düzeyde yetkinlik kazandıran sağlık bilimidir.'],
            ['name' => 'Tıp Mühendisliği', 'desc' => 'Mühendislik prensiplerini tıp dünyasına uygulayarak; yapay organlar, protezler ve ileri tanı-tedavi cihazları geliştiren teknik daldır.'],
            ['name' => 'Turizm İşletmeciliği', 'desc' => 'Otel, acente ve tatil köyü gibi turistik tesislerin yönetimi, pazarlanması ve müşteri hizmetleri operasyonlarını koordine eden bölümdür.'],
            ['name' => 'Turizm Rehberliği', 'desc' => 'Turist gruplarına tarihi, kültürel ve doğal mekanlar hakkında uzmanlık düzeyinde bilgi veren ve seyahat sürecini yöneten profesyonel alandır.'],
            ['name' => 'Türk Dili ve Edebiyatı', 'desc' => 'Türk dilinin yapısını, tarihsel gelişimini ve Türk kültürünün ürettiği edebi eserleri akademik ve eleştirel bir dille inceleyen bölümdür.'],
            ['name' => 'Türk Dili ve Edebiyatı Öğretmenliği', 'desc' => 'Lise seviyesinde dil ve edebiyat eğitimi vermek üzere; pedagoji, dil bilgisi ve edebiyat tarihi üzerine uzmanlaşmış eğitimciler yetiştirir.'],
            ['name' => 'Türkçe Öğretmenliği', 'desc' => 'Ortaokul düzeyindeki öğrencilere ana dil bilincini kazandırmak, okuma, yazma ve konuşma becerilerini geliştirmek amacıyla öğretmenler yetiştiren branştır.'],
            ['name' => 'Uçak Bakım ve Onarım', 'desc' => 'Hava araçlarının motor, gövde ve elektronik sistemlerinin periyodik kontrollerini yapan ve arızalarını gidererek uçuş emniyetini sağlayan teknik bölümdür.'],
            ['name' => 'Uçak Mühendisliği', 'desc' => 'Hava araçlarının aerodinamik yapısını, motor sistemlerini ve performansını tasarlayan, analiz eden ve üretim süreçlerini yöneten mühendislik dalıdır.'],
            ['name' => 'Uluslararası Finans', 'desc' => 'Küresel piyasalardaki sermaye akışlarını, döviz kurlarını, uluslararası yatırım araçlarını ve çok uluslu şirketlerin finansal yönetim stratejilerini inceleyen bölümdür.'],
            ['name' => 'Uluslararası İlişkiler', 'desc' => 'Devletler arası siyasi, ekonomik ve hukuki etkileşimleri, diplomasi tarihini, küresel örgütlerin yapısını ve dünya politikasındaki güç dengelerini araştıran disiplindir.'],
            ['name' => 'Uluslararası Ticaret ve Lojistik', 'desc' => 'Ürün ve hizmetlerin sınırlar ötesi dolaşımını, gümrük mevzuatını, küresel tedarik zinciri yönetimini ve taşımacılık operasyonlarını kapsayan iş dünyası alanıdır.'],
            ['name' => 'Veterinerlik', 'desc' => 'Evcil, çiftlik, egzotik ve yaban hayvanlarının sağlığını koruyan, hastalıklarını teşhis ve tedavi eden, ayrıca hayvansal gıda güvenliği ve toplum sağlığı üzerine uzmanlaşan tıp dalıdır.'],
            ['name' => 'Yapay Zeka Mühendisliği', 'desc' => 'Makinelerin veriden öğrenmesini, akıl yürütmesini ve karmaşık problemleri çözmesini sağlayan algoritmalar, sinir ağları ve akıllı sistemler tasarlayan ileri teknoloji mühendisliğidir.'],
            ['name' => 'Yapay Zeka ve Veri Mühendisliği', 'desc' => 'Yapay zeka modelleri geliştirmenin yanı sıra; büyük veri setlerinin toplanması, temizlenmesi, depolanması ve bu verilerden anlamlı bilgiler çıkarılması süreçlerine odaklanan disiplindir.'],
            ['name' => 'Yazılım Geliştirme', 'desc' => 'Kullanıcı ihtiyaçlarına yönelik bilgisayar programlarının ve mobil uygulamaların tasarımı, kodlanması, test edilmesi ve yayına alınması süreçlerine odaklanan pratik ağırlıklı bölümdür.'],
            ['name' => 'Yazılım Mühendisliği', 'desc' => 'Karmaşık ve büyük ölçekli yazılım sistemlerinin mühendislik prensipleriyle (tasarım, mimari, güvenlik, sürdürülebilirlik) sistematik bir şekilde geliştirilmesini ve yönetilmesini sağlayan daldır.'],
            ['name' => 'Yeni Medya ve İletişim', 'desc' => 'Dijital teknolojilerle dönüşen iletişim mecralarını, sosyal medyayı, internet gazeteciliğini, dijital reklamcılığı ve etkileşimli içerik üretimini kuramsal ve uygulamalı olarak inceleyen alandır.'],
            ['name' => 'Yerel Yönetimler', 'desc' => 'Belediyeler ve il özel idareleri gibi yerel yönetim birimlerinin idari yapısını, kamu hizmetlerinin halka sunulma süreçlerini ve kentsel yönetim politikalarını ele alan disiplindir.'],
            ['name' => 'Yönetim Bilişim Sistemleri (MIS)', 'desc' => 'İşletme yönetimi ile bilişim teknolojilerini birleştiren; veriyi stratejik karar verme süreçlerinde kullanmak için bilgi sistemleri tasarlayan ve yöneten köprü bölümdür.'],
            ['name' => 'Zootekni', 'desc' => 'Çiftlik hayvanlarının genetik ıslahı, beslenmesi, barındırılması ve hayvansal üretimin (et, süt, yumurta vb.) verimliliği ile kalitesini artırma üzerine odaklanan bilim dalıdır.'],
        ];
        

        $onLisansMajors = [
            ['name' => 'Acil Durum ve Afet Yönetimi', 'description' => 'Deprem, yangın, sel gibi afetlerin öncesinde planlama yapma ve afet anında arama-kurtarma ile koordinasyon süreçlerini yönetme eğitimidir.'],
            ['name' => 'Adalet', 'description' => 'Mahkemelerde ve hukuk bürolarında yazı işleri, dosyalama ve temel hukuk süreçlerinin yürütülmesinde görev alacak ara elemanlar yetiştirir.'],
            ['name' => 'Ağız ve Diş Sağlığı', 'description' => 'Diş hekimine muayene ve cerrahi işlemler sırasında yardımcı olan, tıbbi malzemeleri hazırlayan ve hasta bakımını destekleyen teknikerlik bölümüdür.'],
            ['name' => 'Alternatif Enerji Kaynakları Teknolojisi', 'description' => 'Güneş, rüzgar ve jeotermal gibi yenilenebilir enerji sistemlerinin montajı, bakımı ve işletilmesi üzerine uzmanlık kazandırır.'],
            ['name' => 'Ameliyathane Hizmetleri', 'description' => 'Ameliyat öncesi ortamın sterilizasyonunu sağlayan, cerrahi operasyon sırasında doktora gerekli aletleri sunan ve teknik destek veren daldır.'],
            ['name' => 'Anestezi', 'description' => 'Operasyon öncesinde hastanın uyutulması (anestezi) ve operasyon boyunca hayati bulgularının takip edilmesi süreçlerinde anestezi doktoruna eşlik eden teknikerliktir.'],
            ['name' => 'Aşçılık', 'description' => 'Mutfak teknikleri, yemek pişirme yöntemleri ve mutfak yönetimi konusunda uygulamalı eğitim vererek profesyonel mutfak personeli yetiştirir.'],
            ['name' => 'Atık Yönetimi', 'description' => 'Çöplerin ve endüstriyel atıkların toplanması, geri dönüştürülmesi ve çevreye zarar vermeden yok edilmesi süreçlerini yasal mevzuatlara göre yönetir.'],
            ['name' => 'Bahçe Tarımı', 'description' => 'Meyve, sebze ve süs bitkilerinin yetiştirilmesi, seracılık teknikleri ve bahçe bakımı konularında teknik bilgi ve uygulama yetisi kazandırır.'],
            ['name' => 'Bankacılık ve Sigortacılık', 'description' => 'Finans sektöründe customer ilişkileri, kredi işlemleri ve sigorta poliçelerinin satışı/yönetimi süreçlerinde görev alacak personel yetiştirir.'],
            ['name' => 'Bilgisayar Destekli Tasarım ve Animasyon', 'description' => 'Bilgisayar yazılımları kullanarak 2 boyutlu ve 3 boyutlu grafik tasarımı, karakter modelleme ve görsel efekt üretimi yapılan bölümdür.'],
            ['name' => 'Bilgisayar Programcılığı', 'description' => 'Çeşitli yazılım dilleriyle kod yazma, veri tabanı yönetimi ve web uygulamaları geliştirme üzerine yoğunlaşan teknik eğitimdir.'],
            ['name' => 'Bilişim Güvenliği Teknolojisi', 'description' => 'Bilgisayar ağlarını ve verileri siber saldırılara karşı korumak için güvenlik protokolleri geliştiren ve sistem açıklarını denetleyen daldır.'],
            ['name' => 'Bitki Koruma', 'description' => 'Tarımsal üretimde bitkilere zarar veren hastalık ve böceklerle mücadele yöntemleri, ilaçlama teknikleri ve sağlıklı üretim üzerine odaklanır.'],
            ['name' => 'Biyokimya', 'description' => 'Canlı organizmalardaki kimyasal süreçlerin laboratuvar ortamında analiz edilmesi ve tıbbi/endüstriyel araştırmalarda bu verilerin kullanılması alanıdır.'],
            ['name' => 'Biyomedikal Cihaz Teknolojisi', 'description' => 'Hastanelerde kullanılan tıbbi cihazların (emar, röntgen, diyaliz vb.) kurulumu, periyodik bakımı ve arıza onarımını yapan teknik daldır.'],
            ['name' => 'Büro Yönetimi ve Yönetici Asistanlığı', 'description' => 'Kurumsal iletişim, dosyalama sistemleri ve üst düzey yöneticilerin çalışma takvimlerinin organize edilmesi süreçlerini yönetir.'],
            ['name' => 'Çevre Koruma ve Kontrol', 'description' => 'Hava, su ve toprak kirliliğinin ölçülmesi, arıtma tesislerinin işletilmesi ve çevre kirliliğini önleyici denetimlerin yapılmasıyla ilgilenir.'],
            ['name' => 'Çevre Sağlığı', 'description' => 'Çevresel faktörlerin (su kalitesi, atıklar, haşereler vb.) insan sağlığı üzerindeki etkilerini inceleyen ve koruyucu sağlık denetimleri yapan bölümdür.'],
            ['name' => 'Ceza İnfaz ve Güvenlik Hizmetleri', 'description' => 'Cezaevlerinde ve tutukevlerinde güvenliğin sağlanması, mahkumların yönetimi ve ıslah süreçlerinde görev alacak personel yetiştirir.'],
            ['name' => 'Çocuk Gelişimi', 'description' => '0-18 yaş arası çocukların fiziksel, zihinsel ve duygusal gelişim takibini yapan, eğitim materyalleri hazırlayan ve ailelere danışmanlık veren teknikerliktir.'],
            ['name' => 'Coğrafi Bilgi Sistemleri', 'description' => 'Yeryüzüne ait verilerin uydu ve haritalama yazılımlarıyla dijital ortama aktarılması, analiz edilmesi ve görselleştirilmesi sürecini kapsar.'],
            ['name' => 'Çok Boyutlu Modelleme ve Animasyon', 'description' => 'Oyun, film ve simülasyon sektörleri için ileri düzey 3D modeller, mekan tasarımları ve hareketli görüntüler hazırlayan uzmanlık alanıdır.'],
            ['name' => 'Deniz Ulaştırma ve İşletme', 'description' => 'Gemilerde vardiya zabitliği yapacak, gemi yönetimi ve denizcilik kuralları konusunda eğitim alan güverte odaklı bölümdür.'],
            ['name' => 'Deniz ve Liman İşletmeciliği', 'description' => 'Limanlardaki lojistik operasyonlar, yükleme-boşaltma hizmetleri ve gemi acenteliği süreçlerinin yönetimini konu alır.'],
            ['name' => 'Dezenfeksiyon, Sterilizasyon ve Antisepsi Teknikerliği', 'description' => 'Tıbbi aletlerin ve hastane ortamının mikroplardan arındırılması, sterilizasyon cihazlarının kullanılması üzerine uzmanlaşan sağlık dalıdır.'],
            ['name' => 'Dijital Fabrika Teknolojileri', 'description' => 'Endüstri 4.0 kapsamında akıllı üretim sistemleri, sanal fabrika modelleri ve üretim otomasyonu teknolojileri üzerine eğitim verir.'],
            ['name' => 'Diş Protez Teknolojisi', 'description' => 'Diş hekimlerinin aldığı ölçülere göre protez diş, köprü ve ağız içi apareylerin laboratuvar ortamında üretimini yapan teknik bölümdür.'],
            ['name' => 'Dış Ticaret', 'description' => 'İthalat ve ihracat operasyonları, gümrükleme işlemleri, uluslararası ödeme yöntemleri ve lojistik süreçlerinin takibini yapan alandır.'],
            ['name' => 'Diyaliz', 'description' => 'Böbrek yetmezliği yaşayan hastaların diyaliz makinesine bağlanması, tedavi sürecinin takibi ve makine bakımından sorumlu sağlık teknikerliğidir.'],
            ['name' => 'Doğalgaz ve Tesisatı Teknolojisi', 'description' => 'Isıtma, soğutma ve doğalgaz tesisatlarının projelendirilmesi, döşenmesi ve sistemlerin bakım-onarım işlemlerini kapsar.'],
            ['name' => 'E-Ticaret ve Pazarlama', 'description' => 'İnternet üzerinden ürün satışı, dijital pazarlama stratejileri, sosyal medya yönetimi ve müşteri deneyimi analizleri üzerine odaklanır.'],
            ['name' => 'Eczane Hizmetleri', 'description' => 'Eczanelerde ilaçların hazırlanması, stok takibi, reçete kayıtları ve hastalara danışmanlık konularında eczacıya yardımcı olan teknikerliktir.'],
            ['name' => 'Elektrik', 'description' => 'Bina ve sanayi tesislerindeki elektrik tesisatlarının kurulması, elektrikli makinelerin bakımı ve enerji dağıtım sistemlerinin işletilmesi üzerine eğitim verir.'],
            ['name' => 'Elektrik Enerjisi Üretim, İletim ve Dağıtımı', 'description' => 'Enerji santrallerinde elektrik üretilmesi, yüksek gerilim hatlarıyla taşınması ve şehir şebekelerine dağıtılması süreçlerinde teknik operasyonları yöneten bölümdür.'],
            ['name' => 'Elektrikli Cihaz Teknolojisi', 'description' => 'Evlerde veya sanayide kullanılan elektrikli aletlerin kurulumu, bakım-onarımı ve teknik servis hizmetleri üzerine uzmanlık kazandırır.'],
            ['name' => 'Elektronik Haberleşme Teknolojisi', 'description' => 'Telefon, internet, radyo, televizyon ve uydu sistemleri gibi iletişim altyapılarının kurulumu ve işletilmesi süreçlerini kapsar.'],
            ['name' => 'Elektronik Teknolojisi', 'description' => 'Elektronik devrelerin tasarımı, endüstriyel kartların onarımı ve mikroişlemci tabanlı sistemlerin bakımı üzerine odaklanan teknik daldır.'],
            ['name' => 'Elektronörofizyoloji', 'description' => 'Beyin ve sinir sistemiyle ilgili testlerin (EEG, EMG, uyku analizi vb.) uzman doktor gözetiminde uygulanmasını sağlayan sağlık teknikerliği alanıdır.'],
            ['name' => 'Emlak Yönetimi', 'description' => 'Gayrimenkullerin pazarlanması, ekspertiz işlemleri, tapu süreçleri ve mülk yönetimi konularında profesyonel yetkinlik kazandırır.'],
            ['name' => 'Endüstri Ürünleri Tasarımı', 'description' => 'Seri üretim için planlanan eşyaların (mobilya, beyaz eşya, araç içi ekipman vb.) estetik, ergonomik ve işlevsel tasarımını yapmayı öğretir.'],
            ['name' => 'Endüstriyel Kalıpçılık', 'description' => 'Seri üretimde kullanılan metal veya plastik parçaların döküleceği kalıpların tasarımını ve bilgisayarlı makinelerle (CNC) üretimini kapsar.'],
            ['name' => 'Enerji Tesisleri İşletmeciliği', 'description' => 'Enerji üreten tesislerin (santrallerin) idari ve teknik operasyonlarını, verimlilik ve güvenlik standartlarına göre yöneten uzmanlık alanıdır.'],
            ['name' => 'Engelli Bakımı ve Rehabilitasyon', 'description' => 'Bedensel veya zihinsel engelli bireylerin yaşam kalitesini artırmak için günlük bakımlarını yapan ve fiziksel gelişimlerini destekleyen bölümdür.'],
            ['name' => 'Fizyoterapi', 'description' => 'Yaralanma veya hastalık sonrası hareket kısıtlılığı yaşayan bireylere, fizyoterapist eşliğinde egzersiz ve fizik tedavi tekniklerini uygulayan teknikerliktir.'],
            ['name' => 'Fotoğrafçılık ve Kameramanlık', 'description' => 'Işık, kompozisyon ve çekim tekniklerini kullanarak profesyonel fotoğraf ve video çekimi ile kurgu süreçlerini yöneten sanat dalıdır.'],
            ['name' => 'Geleneksel El Sanatları', 'description' => 'Dokuma, ebru, çini, seramik ve ahşap işçiliği gibi kültürel mirasımız olan sanat dallarının tekniklerini öğreten ve uygulayan bölümdür.'],
            ['name' => 'Gemi İnşaatı', 'description' => 'Tersanelerde gemilerin gövde yapılarının montajı, kaynak işleri ve tasarım projelerinin sahada uygulanması süreçlerini yöneten teknik daldır.'],
            ['name' => 'Gemi Makineleri İşletme', 'description' => 'Gemilerin motorlarının ve diğer mekanik sistemlerinin çalışma düzenini sağlayan, periyodik bakım ve onarımlarını yapan uzmanlık alanıdır.'],
            ['name' => 'Geoteknik', 'description' => 'İnşaat yapılacak arazilerin zemin yapısını inceleyen, sondaj verilerini analiz eden ve güvenli temel inşası için veri sağlayan teknik bölümdür.'],
            ['name' => 'Gıda Kalite Kontrolü ve Analizi', 'description' => 'Gıdaların üretim aşamasından tüketime kadar olan süreçte hijyen, içerik ve standartlara uygunluğunu laboratuvar ortamında denetleyen daldır.'],
            ['name' => 'Gıda Teknolojisi', 'description' => 'Tarımsal ham maddelerin işlenerek gıda maddesine dönüştürülmesi, ambalajlanması ve depolanması süreçlerinde teknik denetim yapan alandır.'],
            ['name' => 'Giyim Üretim Teknolojisi', 'description' => 'Hazır giyim sektöründe kalıp hazırlama, dikim teknikleri ve üretim planlaması süreçlerini yöneten teknik uzmanlık dalıdır.'],
            ['name' => 'Görsel İletişim', 'description' => 'Grafik tasarım, dijital medya ve yayıncılık alanlarında mesajın görsel yollarla en etkili şekilde iletilmesi için içerik tasarlayan bölümdür.'],
            ['name' => 'Grafik Tasarımı', 'description' => 'Kurumsal kimlik, logo, ambalaj ve reklam görsellerini estetik ve teknik kurallar çerçevesinde dijital ortamda tasarlayan sanat dalıdır.'],
            ['name' => 'Halkla İlişkiler ve Tanıtım', 'description' => 'Kurumların dış dünyayla iletişimini yöneten, organizasyonlar düzenleyen ve marka imajını güçlendiren faaliyetleri kapsar.'],
            ['name' => 'Harita ve Kadastro', 'description' => 'Arazi ölçümleri yaparak harita taslakları hazırlayan ve taşınmazların hukuki sınırlarını belirleyen (kadastro) teknik teknikerliktir.'],
            ['name' => 'Hasta Bakımı', 'description' => 'Hastanelerde veya evde bakıma muhtaç bireylerin günlük temel ihtiyaçlarını, kişisel bakımlarını ve sağlık takibini yapan meslek dalıdır.'],
            ['name' => 'Hava Lojistiği', 'description' => 'Havayolu taşımacılığında kargo yönetimi, gümrükleme, depolama ve uçuş operasyonlarının yer hizmetleri koordinasyonunu sağlayan daldır.'],
            ['name' => 'Hibrid ve Elektrikli Taşıtlar Teknolojisi', 'description' => 'Yeni nesil elektrikli araçların batarya sistemleri, elektrik motorları ve elektronik aksamlarının bakımı ve onarımı üzerine uzmanlaşır.'],
            ['name' => 'İç Mekan Tasarımı', 'description' => 'Konut, ofis veya mağaza gibi iç mekanların estetik ve fonksiyonel şekilde düzenlenmesi için projeler hazırlayan ve uygulayan bölümdür.'],
            ['name' => 'İklimlendirme ve Soğutma Teknolojisi', 'description' => 'Klima, buzdolabı ve merkezi havalandırma sistemlerinin kurulumu, montajı ve arıza giderimi üzerine eğitim veren teknik daldır.'],
            ['name' => 'İkram Hizmetleri', 'description' => 'Turizm ve gastronomi sektöründe yiyecek-içecek sunumu, servis teknikleri ve organizasyon yönetimi konularında profesyoneller yetiştirir.'],
            ['name' => 'İlahiyat (Önlisans)', 'description' => 'İslam dininin temel kaynaklarını, inanç esaslarını ve ibadet konularını temel düzeyde öğreterek diyanet hizmetlerinde görev alacak kişiler yetiştirir.'],
            ['name' => 'İlk ve Acil Yardım', 'description' => 'Kaza veya hastalık anında olay yerinde ilk müdahaleyi yapan ve hastayı güvenle hastaneye ulaştıran (paramedik) sağlık branşıdır.'],
            ['name' => 'İnşaat Teknolojisi', 'description' => 'Bina, yol ve baraj gibi inşaat projelerinin şantiyede uygulanmasını, denetlenmesini ve metraj-keşif işlemlerini yürüten teknik bölümdür.'],
            ['name' => 'İnsan Kaynakları Yönetimi', 'description' => 'Şirketlerin personel işe alımı, özlük hakları, maaş yönetimi ve eğitim planlaması gibi süreçlerini koordine eden idari daldır.'],
            ['name' => 'İnsansız Hava Aracı Teknolojisi Operatörlüğü', 'description' => 'İHA (Drone) sistemlerinin uçuş operasyonlarını yöneten, teknik bakımını yapan ve veri toplama süreçlerini yürüten bölümdür.'],
            ['name' => 'İnternet ve Ağ Teknolojileri', 'description' => 'Bilgisayar ağlarının kurulumu, sunucu yönetimi, web tasarımı ve ağ güvenliği sistemlerinin işletilmesini kapsayan bilişim alanıdır.'],
            ['name' => 'İş Makineleri Operatörlüğü', 'description' => 'Ekskavatör, vinç ve loder gibi ağır iş makinelerini güvenli şekilde kullanan ve temel bakımını yapabilen uzmanlar yetiştirir.'],
            ['name' => 'İş Sağlığı ve Güvenliği', 'description' => 'Çalışma ortamlarındaki riskleri belirleyen, iş kazalarını önlemek için tedbirler alan ve yasal mevzuata göre denetim yapan daldır.'],
            ['name' => 'İş ve Uğraşı Terapisi (Ergoterapi)', 'description' => 'Günlük yaşam aktivitelerinde zorluk çeken bireylerin bağımsız hareket edebilmesi için yardımcı yöntemler ve terapiler uygulayan sağlık alanıdır.'],
            ['name' => 'İşletme Yönetimi', 'description' => 'Küçük ve orta ölçekli işletmelerin finans, pazarlama, yönetim ve organizasyon süreçlerini yürütebilecek yetkinlik kazandırır.'],
            ['name' => 'Kaynak Teknolojisi', 'description' => 'Metal parçaların farklı kaynak yöntemleriyle (gazaltı, ark vb.) birleştirilmesi, kalite kontrolü ve kaynaklı imalat tasarımı üzerine odaklanan daldır.'],
            ['name' => 'Kimya Teknolojisi', 'description' => 'Kimyasal maddelerin analiz edilmesi, laboratuvar ortamında testlerin yapılması ve endüstriyel kimya üretim süreçlerinin kontrol edilmesi üzerine odaklanan teknik bölümdür.'],
            ['name' => 'Kontrol ve Otomasyon Teknolojisi', 'description' => 'Sanayide kullanılan otomatik üretim sistemlerinin, robotik teknolojilerin ve PLC tabanlı kontrol düzeneklerinin tasarımı, montajı ve bakımıyla ilgilenir.'],
            ['name' => 'Kozmetik Teknolojisi', 'description' => 'Makyaj malzemeleri, kremler, parfümler ve kişisel bakım ürünlerinin formülasyonu, üretimi ve kalite kontrol süreçlerini kapsayan alandır.'],
            ['name' => 'Kültürel Miras ve Turizm', 'description' => 'Tarihi ve kültürel eserlerin korunması, bu değerlerin turizme kazandırılması ve kültürel rotaların yönetimi konularında uzmanlık kazandırır.'],
            ['name' => 'Kuyumculuk ve Takı Tasarımı', 'description' => 'Değerli maden ve taşların işlenmesi, mücevher tasarımı teknikleri ve geleneksel/modern takı üretim yöntemlerini öğreten sanat dalıdır.'],
            ['name' => 'Laborant ve Veteriner Sağlık', 'description' => 'Hayvan hastalıklarının teşhisi için laboratuvar analizleri yapan, kliniklerde veteriner hekime yardımcı olan ve hayvan sağlığı takibini yürüten teknikerliktir.'],
            ['name' => 'Laboratuvar Teknolojisi', 'description' => 'Gıda, su, toprak veya endüstriyel ürünlerin fiziksel ve kimyasal analizlerinin laboratuvar ortamında, bilimsel standartlara göre yapılmasını sağlayan daldır.'],
            ['name' => 'Lojistik', 'description' => 'Ürünlerin üretimden tüketiciye ulaşana kadar olan nakliye, depolama, gümrükleme ve tedarik zinciri süreçlerini planlayan ve yöneten disiplindir.'],
            ['name' => 'Maden Teknolojisi', 'description' => 'Maden sahalarının işletilmesi, cevher çıkarma teknikleri ve çıkarılan madenlerin zenginleştirilmesi süreçlerinde teknik destek veren bölümdür.'],
            ['name' => 'Makine', 'description' => 'Her türlü makine ve mekanik sistemin tasarım projelerine destek veren, üretim aşamasında çalışan ve bu sistemlerin bakım-onarımını yapan teknik daldır.'],
            ['name' => 'Makine Resim ve Konstrüksiyonu', 'description' => 'Makine parçalarının teknik çizimlerini (CAD) hazırlayan, tasarım projelerini hayata geçiren ve mekanik sistemlerin yapısal planlamasını yapan uzmanlık alanıdır.'],
            ['name' => 'Maliye (Ön Lisans)', 'description' => 'Vergi dairesi, defterdarlık veya şirketlerin muhasebe birimlerinde vergi, bütçe ve kamu gelir-gider süreçlerini takip eden personel yetiştirir.'],
            ['name' => 'Medya ve İletişim', 'description' => 'Dijital içerik üretimi, haber yazımı, temel fotoğrafçılık ve video kurgu gibi iletişim becerilerini modern medya kanallarına uygun şekilde kazandıran bölümdür.'],
            ['name' => 'Mekatronik', 'description' => 'Makine, elektronik ve yazılım sistemlerini bir arada kullanarak akıllı cihazlar, robotlar ve modern sanayi makineleri geliştiren disiplindir.'],
            ['name' => 'Metalurji', 'description' => 'Metallerin ve alaşımların ham maddeden son ürüne dönüştürülmesi, döküm teknikleri ve metal kalite analizleri üzerine odaklanan mühendislik destek dalıdır.'],
            ['name' => 'Mimari Restorasyon', 'description' => 'Tarihi yapıların aslına uygun şekilde onarılması, rölöve projelerinin hazırlması ve restorasyon uygulama süreçlerinin teknik yönetimini kapsar.'],
            ['name' => 'Mobil Teknolojiler', 'description' => 'Akıllı telefonlar ve tabletler için uygulama geliştirme (iOS/Android), mobil oyun tasarımı ve mobil sistemlerin altyapısı üzerine eğitim verir.'],
            ['name' => 'Mobilya ve Dekorasyon', 'description' => 'Ahşap esaslı mobilyaların tasarımı, üretimi, iç mekan dekorasyon projelerinin hazırlanması ve montaj süreçlerini yöneten alandır.'],
            ['name' => 'Moda Tasarımı', 'description' => 'Tekstil ürünleri ve aksesuarlar için özgün tasarımlar hazırlayan, kalıp çıkaran ve hazır giyim üretim süreçlerini takip eden yaratıcı daldır.'],
            ['name' => 'Muhasebe ve Vergi Uygulamaları', 'description' => 'Şirketlerin ticari kayıtlarını tutan, beyanname hazırlayan ve mali tabloları yasal mevzuata göre düzenleyen uzmanlık alanıdır.'],
            ['name' => 'Nükleer Teknoloji ve Radyasyon Güvenliği', 'description' => 'Nükleer santrallerde ve radyasyonla çalışılan alanlarda güvenliği sağlayan, doz ölçümü yapan ve teknik süreçleri takip eden uzmanlık dalıdır.'],
            ['name' => 'Nükleer Tıp Teknikleri', 'description' => 'Hastanelerin nükleer tıp birimlerinde görüntüleme ve tedavi amaçlı kullanılan radyoaktif maddelerin hazırlanması ve cihazların (PET-CT vb.) kullanımını kapsar.'],
            ['name' => 'Odyometri', 'description' => 'İşitme kaybı yaşayan hastalara uzman doktor gözetiminde işitme testleri (odyogram) uygulayan ve işitme cihazlarının uygulanmasında görev alan teknikerliktir.'],
            ['name' => 'Optisyenlik', 'description' => 'Göz doktoru tarafından yazılan reçetelere göre gözlük camı ve çerçevesi hazırlayan, kontakt lens satışı ve montajı yapan sağlık branşıdır.'],
            ['name' => 'Organik Tarım', 'description' => 'Hiçbir kimyasal gübre veya ilaç kullanmadan, doğaya saygılı tarımsal üretim yapılması ve bu ürünlerin sertifikalandırılması süreçlerini yöneten daldır.'],
            ['name' => 'Ormancılık ve Orman Ürünleri', 'description' => 'Ormanların korunması, ağaçlandırılması, kereste ve diğer orman ürünlerinin işlenmesi ile ekosistem yönetimi üzerine odaklanan teknik bölümdür.'],
            ['name' => 'Ortopedik Protez ve Ortez', 'description' => 'Uzuv kaybı yaşayanlara yapay organ (protez) veya kas-iskelet sistemi sorunlarını destekleyici cihazlar (ortez) tasarlayıp üreten sağlık teknolojisi dalıdır.'],
            ['name' => 'Otomotiv Gövde ve Yüzey İşlem Teknolojileri', 'description' => 'Araçların şasisi, gövde onarımı, boya uygulamaları ve dış yüzey yenileme süreçleri üzerine uzmanlık kazandırır.'],
            ['name' => 'Otomotiv Teknolojisi', 'description' => 'Motorlu taşıtların mekanik, elektrikli ve elektronik sistemlerinin arıza teşhisi, periyodik bakımı ve onarımı üzerine eğitim veren teknik bölümdür.'],
            ['name' => 'Özel Güvenlik ve Koruma', 'description' => 'Binaların, kişilerin veya etkinliklerin güvenliğini sağlamak için yasal mevzuat, savunma teknikleri ve güvenlik cihazları üzerine eğitim alan meslek dalıdır.'],
            ['name' => 'Pastacılık ve Ekmekçilik', 'description' => 'Unlu mamuller, tatlılar, pastalar ve ekmek çeşitlerinin uluslararası tekniklerle profesyonel düzeyde hazırlanması ve sunulması üzerine yoğunlaşır.'],
            ['name' => 'Patoloji Laboratuvar Teknikleri', 'description' => 'Hastanelerde biyopsi ile alınan doku ve hücre örneklerini mikroskobik incelemeye hazır hale getiren sağlık teknikerliği alanıdır.'],
            ['name' => 'Pazarlama', 'description' => 'Ürün ve hizmetlerin satışını artırmak için pazar araştırması yapan, müşteri ilişkilerini yöneten ve satış stratejileri geliştiren iş dünyası dalıdır.'],
            ['name' => 'Peyzaj ve Süs Bitkileri Yetiştiriciliği', 'description' => 'Dış mekanların düzenlenmesi için kullanılan bitkilerin üretilmesi, bakımı ve bahçe düzenleme uygulamalarını kapsayan teknik bölümdür.'],
            ['name' => 'Radyo ve Televizyon Programcılığı', 'description' => 'TV ve radyo kanallarında program yapımcılığı, yönetmenlik, ses/ışık teknikleri ve yayıncılık operasyonlarını yöneten daldır.'],
            ['name' => 'Radyoterapi', 'description' => 'Kanser tedavisi gören hastaların doktor tarafından planlanan ışın tedavilerini (radyasyon) uygulayan ve cihazları yöneten sağlık uzmanlık alanıdır.'],
            ['name' => 'Rafineri ve Petro-Kimya Teknolojisi', 'description' => 'Ham petrolün işlenerek yakıt ve plastik gibi ürünlere dönüştürüldüğü tesislerde üretim ve kalite kontrol süreçlerini yürüten teknikerliktir.'],
            ['name' => 'Raylı Sistemler İşletmeciliği', 'description' => 'Metro, tramvay ve tren ağlarında yolcu trafiği, istasyon yönetimi ve lojistik operasyonların koordinasyonunu sağlayan bölümdür.'],
            ['name' => 'Raylı Sistemler Makine Teknolojisi', 'description' => 'Raylı taşıtların motor, gövde ve diğer mekanik aksamlarının bakım-onarımı ile atölye süreçlerini yöneten teknik daldır.'],
            ['name' => 'Reklamcılık', 'description' => 'Ürün ve markalar için tanıtım stratejileri kuran, metin yazan ve medya planlaması yaparak hedef kitleye ulaşmayı amaçlayan iletişim dalıdır.'],
            ['name' => 'Saç Bakımı ve Güzellik Hizmetleri', 'description' => 'Saç tasarımı, cilt bakımı, makyaj teknikleri ve estetik uygulamalar konusunda profesyonel hizmet sunan uzmanlık alanıdır.'],
            ['name' => 'Sağlık Kurumları İşletmeciliği', 'description' => 'Hastanelerin ve polikliniklerin idari süreçlerini, hasta kabul birimlerini ve tıbbi sekreterlik operasyonlarını yöneten idari daldır.'],
            ['name' => 'Sağlık Turizmi İşletmeciliği', 'description' => 'Yurt dışından tedavi amaçlı gelen hastaların seyahat, konaklama ve hastane süreçlerinin organizasyonunu ve pazarlamasını yapan bölümdür.'],
            ['name' => 'Seracılık', 'description' => 'İklim kontrollü kapalı alanlarda (seralarda) sebze, meyve ve çiçek üretim teknikleri ile modern tarım teknolojileri üzerine uzmanlaşan bölümdür.'],
            ['name' => 'Seramik ve Cam Tasarımı', 'description' => 'Endüstriyel veya sanatsal amaçlı seramik ve cam objelerin tasarımı, fırınlanması ve süslenmesi süreçlerini öğreten sanat dalıdır.'],
            ['name' => 'Siber Güvenlik', 'description' => 'Kurumların bilgisayar ağlarını siber saldırılara karşı koruyan, dijital sistem açıklarını belirleyen ve veri güvenliğini sağlayan uzmanlık alanıdır.'],
            ['name' => 'Sivil Hava Ulaştırma İşletmeciliği', 'description' => 'Havalimanı terminal işletmeciliği, yer hizmetleri, biletleme ve havayolu operasyonlarının idari yönetimini kapsar.'],
            ['name' => 'Sivil Havacılık Kabin Hizmetleri', 'description' => 'Uçuş sırasında yolcu güvenliğini sağlayan, ikram hizmetlerini yürüten ve acil durum prosedürlerini uygulayan kabin memurlarını (hostes/host) yetiştirir.'],
            ['name' => 'Sivil Savunma ve İtfaiyecilik', 'description' => 'Yangınla mücadele, arama-kurtarma operasyonları ve afet durumlarında halkın can ve mal güvenliğini koruyan profesyonel ekipleri yetiştirir.'],
            ['name' => 'Sondaj Teknolojisi', 'description' => 'Yer altındaki su, petrol, doğal gaz veya maden kaynaklarına ulaşmak için kullanılan sondaj makinelerinin kurulumu, işletilmesi ve teknik bakımını yöneten daldır.'],
            ['name' => 'Sosyal Güvenlik', 'description' => 'Emeklilik, sigorta, sağlık hizmetleri ve sosyal yardımlar gibi devletin sunduğu sosyal güvenlik sistemlerinin mevzuatını ve işleyişini yürüten personel yetiştirir.'],
            ['name' => 'Sosyal Hizmetler', 'description' => 'Toplumdaki dezavantajlı bireylerin (çocuklar, yaşlılar, engelliler) yaşam kalitesini artırmak için sosyal destek programları hazırlayan ve uygulayan uzmanlık alanıdır.'],
            ['name' => 'Sosyal Medya Yöneticiliği', 'description' => 'Markaların dijital platformlardaki imajını yöneten, içerik üreten, reklam stratejileri kuran ve takipçi analizleri yapan modern iletişim dalıdır.'],
            ['name' => 'Spor Yönetimi', 'description' => 'Spor tesislerinin işletilmesi, spor organizasyonlarının planlanması ve kulüplerin idari/mali süreçlerinin yönetimi üzerine odaklanan bölümdür.'],
            ['name' => 'Su Altı Teknolojisi', 'description' => 'Profesyonel dalış tekniklerini kullanarak su altında inşaat, bakım-onarım, kaynak ve araştırma işlerini yapan "sanayi dalgıçlarını" yetiştiren teknik daldır.'],
            ['name' => 'Süt ve Ürünleri Teknolojisi', 'description' => 'Sütün toplanmasından peynir, yoğurt, tereyağı gibi ürünlere dönüştürülmesine kadar olan tüm endüstriyel üretim ve kalite kontrol süreçlerini kapsar.'],
            ['name' => 'Tarım Makineleri', 'description' => 'Traktörlerden hasat makinelerine kadar tarımda kullanılan tüm mekanik araçların tasarımı, kullanımı, bakımı ve onarımı üzerine uzmanlık kazandırır.'],
            ['name' => 'Tarla Bitkileri', 'description' => 'Tahıllar, baklagiller ve endüstri bitkilerinin yetiştirilmesi, verimliliğinin artırılması ve hastalıklarla mücadele edilmesi süreçlerini yöneten tarım dalıdır.'],
            ['name' => 'Tekstil Teknolojisi', 'description' => 'Elyafın ipliğe ve kumaşa dönüşme süreçlerini, dokuma/örme tekniklerini ve tekstil makinelerinin işletimini kapsayan teknik bölümdür.'],
            ['name' => 'Tıbbi Dokümantasyon ve Sekreterlik', 'description' => 'Hastanelerde hasta kayıtlarını tutan, tıbbi arşivleri yöneten ve sağlık yönetimi süreçlerinde sekreterlik hizmeti veren uzmanlık alanıdır.'],
            ['name' => 'Tıbbi Görüntüleme Teknikleri', 'description' => 'Hastalıkların teşhisi için kullanılan Röntgen, BT, MR, Ultrason gibi tıbbi görüntüleme cihazlarını kullanan ve çekim yapan teknikerliktir.'],
            ['name' => 'Tıbbi Laboratuvar Teknikleri', 'description' => 'Hastanelerin laboratuvarlarında kan, idrar ve doku gibi örnekleri analiz ederek hastalıkların teşhis edilmesini sağlayan sağlık branşıdır.'],
            ['name' => 'Tıbbi Tanıtım ve Pazarlama', 'description' => 'İlaç ve tıbbi cihazların doktorlara veya sağlık kuruluşlarına tanıtılması ve satış süreçlerinin yönetilmesi üzerine odaklanan "tıbbi mümessillik" alanıdır.'],
            ['name' => 'Tıbbi ve Aromatik Bitkiler', 'description' => 'İlaç, kozmetik ve gıda sektöründe kullanılan bitkilerin (kekik, lavanta vb.) yetiştirilmesi, toplanması ve işlenmesi üzerine uzmanlık kazandırır.'],
            ['name' => 'Turist Rehberliği (Ön Lisans)', 'description' => 'Yerli ve yabancı turistlere tarihi ve kültürel mekanları tanıtan, seyahat gruplarını yöneten ve bölge hakkında bilgi veren profesyonel daldır.'],
            ['name' => 'Turizm ve Otel İşletmeciliği', 'description' => 'Konaklama tesislerinin ön büro, kat hizmetleri ve genel yönetimi gibi operasyonel süreçlerini planlayan ve yürüten bölümdür.'],
            ['name' => 'Turizm ve Seyahat Hizmetleri', 'description' => 'Seyahat acentelerinde tur planlama, biletleme, rezervasyon ve organizasyon hizmetlerini yürüten personel yetiştirir.'],
            ['name' => 'Uçak Teknolojisi', 'description' => 'Hava araçlarının motor, gövde ve elektronik sistemlerinin periyodik bakımını, arıza teşhisini ve onarımını yapan teknik uzmanlık alanıdır.'],
            ['name' => 'Uçuş Harekat Yöneticiliği (Dispatcher)', 'description' => 'Uçuş planlarını hazırlayan, yakıt hesaplaması yapan ve uçuş boyunca pilotla sürekli iletişim kurarak operasyonu takip eden teknik daldır.'],
            ['name' => 'Uygulamalı İngilizce Çevirmenlik', 'description' => 'İngilizce metinlerin çevrilmesi ve sözlü iletişimde tercümanlık yapılması konusunda pratik beceriler kazandıran dil bölümüdür.'],
            ['name' => 'Web Tasarımı ve Kodlama', 'description' => 'İnternet sitelerinin görsel tasarımı (arayüz) ve bu sitelerin çalışmasını sağlayan arka plan yazılım kodlarının geliştirilmesi üzerine yoğunlaşan alandır.'],
            ['name' => 'Yapı Denetimi', 'description' => 'İnşaatların projeye ve yasal standartlara uygunluğunu yerinde denetleyen, güvenli ve dayanıklı yapıların inşasını kontrol eden teknik bölümdür.'],
            ['name' => 'Yapı Tesisat Teknolojisi', 'description' => 'Binalardaki sıhhi tesisat, ısıtma, soğutma ve doğal gaz sistemlerinin projelendirilmesi ve kurulması süreçlerini yönetir.'],
            ['name' => 'Yaşlı Bakımı', 'description' => 'Yaşlı bireylerin fiziksel, sosyal ve psikolojik ihtiyaçlarını karşılayan, tıbbi takiplerini yapan ve yaşam kalitelerini artıran sağlık branşıdır.'],
            ['name' => 'Yat Kaptanlığı', 'description' => 'Ticari veya özel yatlarda gemi yönetimi, seyir, güvenlik ve motor bakımı gibi konularda yetkinlik kazandırarak kaptan yetiştiren bölümdür.'],
            ['name' => 'Yerel Yönetimler', 'description' => 'Belediyelerin idari yapısı, yerel hizmetlerin halka sunulması ve kent yönetimi süreçlerinde görev alacak uzmanlar yetiştirir.'],
        ];

        $languages = ['TR', 'EN'];

        foreach ($lisansMajors as $major) {
            foreach ($languages as $lang) {
                Major::updateOrCreate(
                    [
                        'name' => $major['name'], 
                        'education_language' => $lang
                    ],
                    [
                        'description' => $major['desc'],
                        'degree_type' => 'lisans'
                    ]
                );
            }
        }

        foreach ($onLisansMajors as $majorData) {
            foreach ($languages as $lang) {
                Major::updateOrCreate(
                    [
                        'name' => $majorData['name'], 
                        'education_language' => $lang
                    ],
                    [
                        'description' => $majorData['description'],
                        'degree_type' => 'on_lisans'
                    ]
                );
            }
        }
    }
}